/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTAS;

import DATOS.valicuota;
import LOGICA.falicuota;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author user
 */
public class frmAlicuota extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmAlicuota
     */
    public frmAlicuota() {
        initComponents();
        mostrar("");
        inhabilitar();
    }
    
    
    private void sizetable(){
        
        try {
            TableColumnModel columnModel = tbalicuota.getColumnModel();
            columnModel.getColumn(0).setPreferredWidth(60);
            columnModel.getColumn(1).setPreferredWidth(100);
            columnModel.getColumn(2).setPreferredWidth(100);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error al intentar ajustar la tabla ");
        }
    
    }

    
   private void inhabilitar (){
       //deshabilitar cajas de texto
        txtcodigoAlicuota.setEnabled(false);
        txtvalor.setEnabled(false);
        txtporcentaje.setEnabled(false);
        

        //deshabilitar botones
        btnguardar.setEnabled(false);
        btneliminar.setEnabled(false);
        btnmodificar.setEnabled(false);
        btncancelar.setEnabled(false);
        
        //vaciar cajas de texto

        
    }
   void vaciasCajas(){
        txtcodigoAlicuota.setText("");
        txtvalor.setText("");
        txtporcentaje.setText("");
   }
   
    void habilitar (){
        //habilitar cajas de texto
        txtcodigoAlicuota.setEnabled(true);
        txtvalor.setEnabled(true);
        txtporcentaje.setEnabled(true);
        //habilitar botones
        btnguardar.setEnabled(true);
        btnmenu.setEnabled(true);
        btneliminar.setEnabled(true);
        //vaciar cajas de texto
    }
    
    private void mostrar (String buscar){
        try {
            DefaultTableModel modelo;
            falicuota func= new falicuota();
            modelo=func.mostrarAlicuota(buscar);
            tbalicuota.setModel(modelo);
            lblTotal.setText(""+ Integer.toString(func.totalRegistros));   
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
            
        }
    
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new java.awt.Panel();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnmenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbalicuota = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnbuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblcodigo = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        lblprivilegios = new javax.swing.JLabel();
        txtcodigoAlicuota = new javax.swing.JTextField();
        txtvalor = new javax.swing.JTextField();
        txtporcentaje = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TASA DE IMPUESTOS");
        setMaximumSize(new java.awt.Dimension(540, 470));
        setMinimumSize(new java.awt.Dimension(540, 470));
        setPreferredSize(new java.awt.Dimension(540, 470));
        getContentPane().setLayout(null);

        panel2.setBackground(new java.awt.Color(0, 102, 153));
        panel2.setLayout(null);

        btnnuevo.setBackground(new java.awt.Color(255, 255, 255));
        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/agregar-documento-simbolo-delineado.png"))); // NOI18N
        btnnuevo.setToolTipText("NUEVO REGISTRO");
        btnnuevo.setNextFocusableComponent(txtcodigoAlicuota);
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        panel2.add(btnnuevo);
        btnnuevo.setBounds(0, 0, 50, 50);

        btnguardar.setBackground(new java.awt.Color(255, 255, 255));
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/guardar.png"))); // NOI18N
        btnguardar.setToolTipText("GUARDAR REGISTRO");
        btnguardar.setNextFocusableComponent(btnmodificar);
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        panel2.add(btnguardar);
        btnguardar.setBounds(50, 0, 50, 50);

        btnmodificar.setBackground(new java.awt.Color(255, 255, 255));
        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/archivo-nuevo.png"))); // NOI18N
        btnmodificar.setToolTipText("MODIFICAR REGISTRO");
        btnmodificar.setNextFocusableComponent(btnmodificar);
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        panel2.add(btnmodificar);
        btnmodificar.setBounds(100, 0, 50, 50);

        btncancelar.setBackground(new java.awt.Color(255, 255, 255));
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/expediente.png"))); // NOI18N
        btncancelar.setToolTipText("CANCELAR REGISTRO");
        btncancelar.setNextFocusableComponent(btneliminar);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        panel2.add(btncancelar);
        btncancelar.setBounds(150, 0, 50, 50);

        btneliminar.setBackground(new java.awt.Color(255, 255, 255));
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/cubo-de-basura.png"))); // NOI18N
        btneliminar.setToolTipText("ELIMINAR REGISTRO");
        btneliminar.setNextFocusableComponent(btnmenu);
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        panel2.add(btneliminar);
        btneliminar.setBounds(200, 0, 50, 50);

        btnmenu.setBackground(new java.awt.Color(255, 255, 255));
        btnmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/salida.png"))); // NOI18N
        btnmenu.setText("MENU");
        btnmenu.setToolTipText("IR A MENU");
        btnmenu.setNextFocusableComponent(txtcodigoAlicuota);
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });
        panel2.add(btnmenu);
        btnmenu.setBounds(420, 0, 100, 50);

        getContentPane().add(panel2);
        panel2.setBounds(0, 0, 600, 50);

        tbalicuota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "USUARIO", "CLAVE", "PRIVILEGIOS"
            }
        ));
        tbalicuota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbalicuotaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbalicuota);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 240, 500, 160);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("USUARIOS REGISTRADOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 200, 160, 30);

        txtbuscar.setText(" ");
        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });
        txtbuscar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtbuscarPropertyChange(evt);
            }
        });
        getContentPane().add(txtbuscar);
        txtbuscar.setBounds(340, 200, 120, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("TOTAL DE REGISTROS:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(260, 410, 140, 20);

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 0, 0));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal.setText("0");
        getContentPane().add(lblTotal);
        lblTotal.setBounds(400, 410, 110, 20);

        btnbuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/buscar.png"))); // NOI18N
        btnbuscar.setToolTipText("BUSCAR USUARIO");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnbuscar);
        btnbuscar.setBounds(460, 190, 50, 50);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DETALLE  DE ALICUOTA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.setLayout(null);

        lblcodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcodigo.setText("CODIGO ");
        jPanel1.add(lblcodigo);
        lblcodigo.setBounds(10, 20, 60, 30);

        lblusuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblusuario.setText("VALOR");
        jPanel1.add(lblusuario);
        lblusuario.setBounds(10, 60, 60, 30);

        lblprivilegios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblprivilegios.setText("PORCENTAJE");
        jPanel1.add(lblprivilegios);
        lblprivilegios.setBounds(10, 100, 80, 30);

        txtcodigoAlicuota.setNextFocusableComponent(txtvalor);
        txtcodigoAlicuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoAlicuotaActionPerformed(evt);
            }
        });
        txtcodigoAlicuota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcodigoAlicuotaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcodigoAlicuotaKeyReleased(evt);
            }
        });
        jPanel1.add(txtcodigoAlicuota);
        txtcodigoAlicuota.setBounds(100, 20, 130, 30);

        txtvalor.setNextFocusableComponent(txtporcentaje);
        txtvalor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvalorActionPerformed(evt);
            }
        });
        jPanel1.add(txtvalor);
        txtvalor.setBounds(100, 60, 130, 30);

        txtporcentaje.setNextFocusableComponent(btnguardar);
        txtporcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtporcentajeActionPerformed(evt);
            }
        });
        txtporcentaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtporcentajeKeyPressed(evt);
            }
        });
        jPanel1.add(txtporcentaje);
        txtporcentaje.setBounds(100, 100, 130, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 50, 520, 140);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed

        habilitar();
        vaciasCajas();
        txtcodigoAlicuota.requestFocus();
        btnmodificar.setEnabled(false);
        btnmenu.setEnabled(false);
        btnnuevo.setEnabled(false);
        btneliminar.setEnabled(false);
        btncancelar.setEnabled(true);
        btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        if (txtcodigoAlicuota.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un Codigo para la alicuota");
            txtcodigoAlicuota.requestFocus();
            return;
        }

        if (txtvalor.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un valor de alicuota");
            txtvalor.requestFocus();
            return;
        
        }
        if (txtporcentaje.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes determinar el porcentaje de la alicuota");
            txtporcentaje.requestFocus();
            return;
        }
        try {
            
            valicuota dts= new valicuota();
            falicuota func=new falicuota();

            dts.setCodigoAlicuota(Integer.parseInt(txtcodigoAlicuota.getText()));
            dts.setValor(txtvalor.getText());
            dts.setPorcentaje(Double.parseDouble(txtporcentaje.getText()));

            func.insertar(dts);
            JOptionPane.showMessageDialog(rootPane, "Registro almacenado exitosamente.");
            mostrar("");
            inhabilitar();
            //habilitar botones
            btnmenu.setEnabled(true);
            btnnuevo.setEnabled(true);
            //ihabilitar botones
            btnguardar.setEnabled(false);
            sizetable();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error al intentar insertar el impuesto.");
        }

    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        if (txtcodigoAlicuota.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un Codigo para la alicuota.");
            txtcodigoAlicuota.requestFocus();
            return;
        }

        if (txtvalor.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un valor de alicuota.");
            txtvalor.requestFocus();
            return;
        
        }
        if (txtporcentaje.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes determinar el porcentaje de la alicuota.");
            txtporcentaje.requestFocus();
            return;
        }
        try {
            valicuota dts= new valicuota();
            falicuota func=new falicuota();

            dts.setCodigoAlicuota(Integer.parseInt(txtcodigoAlicuota.getText()));
            dts.setValor(txtvalor.getText());
            dts.setPorcentaje(Double.parseDouble(txtporcentaje.getText()));

            func.modificar(dts);
            mostrar("");
            inhabilitar();
            btnmenu.setEnabled(true);
            sizetable();
            
            JOptionPane.showMessageDialog(rootPane, "Registro modificado exitosamente.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error al intentar modificar el registro.");
        }
        
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Se ha cancelado la operacion.");
        inhabilitar ();
        btnmenu.setEnabled(true);
        btnnuevo.setEnabled(true);
        vaciasCajas();
        mostrar("");
        sizetable();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        if (!txtcodigoAlicuota.getText().equals("")) {

            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Seguro que quiere eliminar este registro?", "Confirmar", 2);

            if (confirmacion==0) {
                try {
                    valicuota dts= new valicuota();
                    falicuota func=new falicuota();

                    dts.setCodigoAlicuota(Integer.parseInt(txtcodigoAlicuota.getText()));
                    func.eliminar(dts);
                    mostrar("");
                    inhabilitar ();
                    btnmenu.setEnabled(true);
                    sizetable();
                    vaciasCajas();
                    JOptionPane.showMessageDialog(rootPane, "Registro eliminado exitosamente");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Error al intentar eliminar el registro!.");
                }
                
            }
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnmenuActionPerformed

    private void tbalicuotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbalicuotaMouseClicked
        // TODO add your handling code here:
        //habilar los elementos para su modificacion
        btnmodificar.setEnabled(true);
        btneliminar.setEnabled(true);
        btncancelar.setEnabled(true);
        btnmenu.setEnabled(false);
        txtcodigoAlicuota.setEnabled(true);
        txtvalor.setEnabled(true);
        txtporcentaje.setEnabled(true);

        int fila =tbalicuota.rowAtPoint(evt.getPoint());
            try {
            txtcodigoAlicuota.setText(tbalicuota.getValueAt(fila, 0).toString());
            txtvalor.setText(tbalicuota.getValueAt(fila, 1).toString());
            txtporcentaje.setText(tbalicuota.getValueAt(fila, 2).toString());
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "Error al intentar cargar los datos a los textFields");
        }

    }//GEN-LAST:event_tbalicuotaMouseClicked

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void txtbuscarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtbuscarPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarPropertyChange

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed

        mostrar(txtbuscar.getText());
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void txtcodigoAlicuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoAlicuotaActionPerformed
        // TODO add your handling code here:
        txtvalor.grabFocus();
    }//GEN-LAST:event_txtcodigoAlicuotaActionPerformed

    private void txtcodigoAlicuotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoAlicuotaKeyPressed

    }//GEN-LAST:event_txtcodigoAlicuotaKeyPressed

    private void txtcodigoAlicuotaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoAlicuotaKeyReleased

    }//GEN-LAST:event_txtcodigoAlicuotaKeyReleased

    private void txtvalorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvalorActionPerformed
        // TODO add your handling code here:
        txtporcentaje.grabFocus();
    }//GEN-LAST:event_txtvalorActionPerformed

    private void txtporcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtporcentajeActionPerformed
        
    }//GEN-LAST:event_txtporcentajeActionPerformed

    private void txtporcentajeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtporcentajeKeyPressed

    }//GEN-LAST:event_txtporcentajeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAlicuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAlicuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAlicuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAlicuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAlicuota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmenu;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JLabel lblprivilegios;
    private javax.swing.JLabel lblusuario;
    private java.awt.Panel panel2;
    private javax.swing.JTable tbalicuota;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtcodigoAlicuota;
    private javax.swing.JTextField txtporcentaje;
    private javax.swing.JTextField txtvalor;
    // End of variables declaration//GEN-END:variables
}
