/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTAS;

import LOGICA.fpaciente;
import static VISTAS.frmmenu.escritorio;
import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author user
 */
public class frmbuscarPaciente extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmbuscarPaciente
     */
    public frmbuscarPaciente() {
        initComponents();
        mostrar(cbparametro.getSelectedItem().toString(),txtbuscar.getText());
        sizetable();
    }
    
    
    private void mostrar (String parametro,String buscar){
        try {
            DefaultTableModel modelo;
            String valor;
            String valorfinal;
            valorfinal="";
            valor= cbparametro.getSelectedItem().toString();
            if (valor=="CEDULA"){
                valorfinal="Cedula";
            }
            if (valor=="CODIGO"){
                valorfinal="codigoPaciente";
            }
            if (valor=="NOMBRE"){
                valorfinal="nombres";
            }
            if (valor=="APELLIDO"){
                valorfinal="apellidos";
            }
            System.out.println(cbparametro.getSelectedItem().toString());
            fpaciente func= new fpaciente();
            
            System.out.println(buscar);
            modelo=func.mostrarPaciente(valorfinal,buscar);
            tbpaciente.setModel(modelo);
            lblTotal.setText(""+ Integer.toString(func.totalRegistros));   
            sizetable();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
            JOptionPane.showConfirmDialog(rootPane, "Error al cargar los registros en la tabla.");
        }
 }
    
        
    private void sizetable(){
        try {
            TableColumnModel columnModel = tbpaciente.getColumnModel();
            columnModel.getColumn(0).setPreferredWidth(0);//codigo
            columnModel.getColumn(1).setPreferredWidth(100);//cedula
            columnModel.getColumn(2).setPreferredWidth(400);//nombre
            columnModel.getColumn(3).setPreferredWidth(400);//apellidos
            columnModel.getColumn(4).setPreferredWidth(0);//fecha nacimiento
            columnModel.getColumn(5).setPreferredWidth(0);//telefono
            columnModel.getColumn(6).setPreferredWidth(0);//direccion
            columnModel.getColumn(7).setPreferredWidth(0);//sexo
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error al ajustar la tabla.");
        }
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbpaciente = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        panel2 = new java.awt.Panel();
        btnmenu = new javax.swing.JButton();
        lblparametro = new javax.swing.JLabel();
        cbparametro = new javax.swing.JComboBox();
        btnbuscar = new javax.swing.JButton();
        btntodos = new javax.swing.JButton();
        btntodos1 = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BUSQUEDA DE PACIENTE");
        setMaximumSize(new java.awt.Dimension(820, 550));
        setMinimumSize(new java.awt.Dimension(820, 550));
        setPreferredSize(new java.awt.Dimension(820, 550));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONSULTA DE  PACIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(960, 450));
        jPanel1.setMinimumSize(new java.awt.Dimension(960, 450));
        jPanel1.setLayout(null);

        tbpaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "CODIGO", "NOMBRE"
            }
        ));
        tbpaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbpacienteMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbpacienteMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbpacienteMouseReleased(evt);
            }
        });
        jScrollPane4.setViewportView(tbpaciente);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(10, 20, 780, 360);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("TOTAL DE REGISTROS:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(550, 380, 140, 30);

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 0, 0));
        lblTotal.setText("0");
        jPanel1.add(lblTotal);
        lblTotal.setBounds(700, 380, 90, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 90, 800, 420);

        panel2.setBackground(new java.awt.Color(0, 102, 153));
        panel2.setLayout(null);

        btnmenu.setBackground(new java.awt.Color(255, 255, 255));
        btnmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/salida.png"))); // NOI18N
        btnmenu.setText("menu");
        btnmenu.setToolTipText("IR A MENU");
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });
        panel2.add(btnmenu);
        btnmenu.setBounds(700, 0, 100, 50);

        lblparametro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblparametro.setForeground(new java.awt.Color(255, 255, 255));
        lblparametro.setText("PARAMETRO DE BUSQUEDA");
        panel2.add(lblparametro);
        lblparametro.setBounds(10, 20, 180, 30);

        cbparametro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CEDULA", "CODIGO", "NOMBRE", "APELLIDO" }));
        cbparametro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbparametroActionPerformed(evt);
            }
        });
        panel2.add(cbparametro);
        cbparametro.setBounds(190, 20, 210, 30);

        btnbuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/buscar.png"))); // NOI18N
        btnbuscar.setToolTipText("BUSCAR REGISTRO");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        panel2.add(btnbuscar);
        btnbuscar.setBounds(560, 0, 70, 50);

        btntodos.setBackground(new java.awt.Color(255, 255, 255));
        btntodos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/equipo.png"))); // NOI18N
        btntodos.setToolTipText("MOSTRAR TODOS");
        btntodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntodosActionPerformed(evt);
            }
        });
        panel2.add(btntodos);
        btntodos.setBounds(630, 0, 70, 50);

        btntodos1.setBackground(new java.awt.Color(255, 255, 255));
        btntodos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/agregar-documento-simbolo-delineado.png"))); // NOI18N
        btntodos1.setText("NUEVO");
        btntodos1.setToolTipText("NUEVO REGISTRO");
        btntodos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntodos1ActionPerformed(evt);
            }
        });
        panel2.add(btntodos1);
        btntodos1.setBounds(450, 0, 110, 50);

        getContentPane().add(panel2);
        panel2.setBounds(0, 0, 1000, 50);

        txtbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtbuscarMousePressed(evt);
            }
        });
        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscarKeyTyped(evt);
            }
        });
        getContentPane().add(txtbuscar);
        txtbuscar.setBounds(10, 60, 770, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbpacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbpacienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbpacienteMouseClicked

    private void tbpacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbpacienteMousePressed
        // TODO add your handling code here:
        if (evt.getClickCount()==2){
            //habilar los elementos para su modificacion
            try {
                int fila =tbpaciente.rowAtPoint(evt.getPoint());
                frmsolicitud.txtcodigoPaciente.setText(tbpaciente.getValueAt(fila, 0).toString());
                frmsolicitud.txtcedulaPaciente.setText(tbpaciente.getValueAt(fila, 1).toString());
                frmsolicitud.txtnombresPaciente.setText(tbpaciente.getValueAt(fila, 2).toString());
                frmsolicitud.txtapellidosPacientes.setText(tbpaciente.getValueAt(fila, 3).toString());
                frmsolicitud.jdfechaNacimiento.setDate(Date.valueOf(tbpaciente.getValueAt(fila, 4).toString()));
                frmsolicitud.txttelefonoPaciente.setText(tbpaciente.getValueAt(fila, 5).toString());
                frmsolicitud.txtdireccionPaciente.setText(tbpaciente.getValueAt(fila, 6).toString());
                if (tbpaciente.getValueAt(fila, 7).toString().equals("MASCULINO")){
                    frmsolicitud.cbsexo.setSelectedIndex(0);
                }
                else{
                    frmsolicitud.cbsexo.setSelectedIndex(1);

                }

                this.dispose();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error al tratar de importar los registros a los textfields.");
            }
        }
    }//GEN-LAST:event_tbpacienteMousePressed

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnmenuActionPerformed

    private void cbparametroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbparametroActionPerformed
        // TODO add your handling code here:
        mostrar("","");
        System.out.println(cbparametro.getSelectedItem().toString());
    }//GEN-LAST:event_cbparametroActionPerformed

    private void txtbuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbuscarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarMousePressed

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void txtbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyPressed

    }//GEN-LAST:event_txtbuscarKeyPressed

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased

    }//GEN-LAST:event_txtbuscarKeyReleased

    private void btntodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntodosActionPerformed
        // TODO add your handling code here:
        txtbuscar.setText("");
        String dato="";
        dato=txtbuscar.getText();
        mostrar(cbparametro.getSelectedItem().toString(),dato);
    }//GEN-LAST:event_btntodosActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        String dato="";
        dato=txtbuscar.getText();
        mostrar(cbparametro.getSelectedItem().toString(),dato);
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btntodos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntodos1ActionPerformed
        // TODO add your handling code here:
        try {
            frmpaciente form = new frmpaciente();
            escritorio.add(form);
            form.toFront();
            form.setSize(720, 270);
            form.setVisible(true); 
            frmpaciente.btnnuevo.doClick();
            frmpaciente.txtcedulaPaciente.setText(frmbuscarPaciente.txtbuscar.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error al intentar abrir el formulario de Pacientes.");
        }
        
    }//GEN-LAST:event_btntodos1ActionPerformed

    private void tbpacienteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbpacienteMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tbpacienteMouseReleased

    private void txtbuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyTyped
         Character c = evt.getKeyChar();
                if(Character.isLetter(c)) {
                    evt.setKeyChar(Character.toUpperCase(c));
                }
    }//GEN-LAST:event_txtbuscarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmbuscarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmbuscarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmbuscarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmbuscarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmbuscarPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnmenu;
    private javax.swing.JButton btntodos;
    private javax.swing.JButton btntodos1;
    private javax.swing.JComboBox cbparametro;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblparametro;
    private java.awt.Panel panel2;
    public static javax.swing.JTable tbpaciente;
    public static javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
