/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTAS;

import LOGICA.finstitucion;
import static VISTAS.frmconsultaInstitucion.tbinstitucion;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author user
 */
public class frmbaremoInstitucion extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmbaremoInstitucion
     */
    public frmbaremoInstitucion() {
        initComponents();
        mostrar("codigoInstitucion","");
        sizetable();
    }
    
    private void mostrar (String parametro,String buscar){
        try {
            DefaultTableModel modelo;
            finstitucion func= new finstitucion();
            modelo=func.mostrarInstitucion2("codigoInstitucion",buscar);
            tbinstitucion.setModel(modelo);
            lblTotal.setText(""+ Integer.toString(func.totalRegistros));   
            sizetable();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "Error al cargar los registros en la tabla");
            JOptionPane.showConfirmDialog(rootPane, e);

        }

    }
    
        
    private void sizetable(){
        
        try {
            TableColumnModel columnModel = tbinstitucion.getColumnModel();
            columnModel.getColumn(0).setPreferredWidth(100);
            columnModel.getColumn(0).setMaxWidth(100);
            columnModel.getColumn(1).setPreferredWidth(700);
            columnModel.getColumn(1).setMaxWidth(700);
            columnModel.getColumn(2).setPreferredWidth(300);
            columnModel.getColumn(2).setMaxWidth(300);
            columnModel.getColumn(3).setPreferredWidth(800);
            columnModel.getColumn(3).setMaxWidth(800);
            columnModel.getColumn(4).setPreferredWidth(300);
            columnModel.getColumn(4).setMaxWidth(300);
            columnModel.getColumn(5).setPreferredWidth(400);
            columnModel.getColumn(5).setMaxWidth(400);
            columnModel.getColumn(6).setPreferredWidth(300);
            columnModel.getColumn(6).setMaxWidth(300);
            columnModel.getColumn(7).setPreferredWidth(300);
            columnModel.getColumn(7).setMaxWidth(300);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "Error al ajustar la tabla");
            JOptionPane.showConfirmDialog(rootPane, e);
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbinstitucion = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        panel2 = new java.awt.Panel();
        btnmenu = new javax.swing.JButton();
        lblparametro = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(690, 530));
        setMinimumSize(new java.awt.Dimension(690, 530));
        setPreferredSize(new java.awt.Dimension(690, 530));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONSULTA DE INSTITUCION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(960, 450));
        jPanel1.setMinimumSize(new java.awt.Dimension(960, 450));
        jPanel1.setLayout(null);

        tbinstitucion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "CODIGO", "NOMBRE"
            }
        ));
        tbinstitucion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbinstitucionMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbinstitucionMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(tbinstitucion);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(10, 30, 650, 390);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("TOTAL DE REGISTROS:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(420, 420, 140, 30);

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 0, 0));
        lblTotal.setText("0");
        jPanel1.add(lblTotal);
        lblTotal.setBounds(570, 420, 90, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 50, 670, 450);

        panel2.setBackground(new java.awt.Color(0, 102, 153));
        panel2.setLayout(null);

        btnmenu.setBackground(new java.awt.Color(255, 255, 255));
        btnmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/salida.png"))); // NOI18N
        btnmenu.setText("MENU");
        btnmenu.setToolTipText("IR A MENU");
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });
        panel2.add(btnmenu);
        btnmenu.setBounds(540, 0, 130, 50);

        lblparametro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblparametro.setForeground(new java.awt.Color(255, 255, 255));
        lblparametro.setText("SELECCIONE UNA INSTITUCION*");
        panel2.add(lblparametro);
        lblparametro.setBounds(20, 10, 210, 30);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel2.add(jButton1);
        jButton1.setBounds(690, 20, 73, 23);

        getContentPane().add(panel2);
        panel2.setBounds(0, 0, 1000, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbinstitucionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbinstitucionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbinstitucionMouseClicked

    private void tbinstitucionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbinstitucionMousePressed
        // TODO add your handling code here:
        if (evt.getClickCount()==2){
            //habilar los elementos para su modificacion

            try {
                frmbaremo form= new  frmbaremo();
                form.toFront();
                frmmenu.escritorio.add(form);
                form.setSize(920, 620);
                form.setVisible(true);
                int fila =tbinstitucion.rowAtPoint(evt.getPoint());
                frmbaremo.txtcodigoInstitucion.setText(tbinstitucion.getValueAt(fila, 0).toString());
                frmbaremo.txtnombreInstitucion.setText(tbinstitucion.getValueAt(fila, 1).toString());
                frmbaremo.btnActualizar.doClick();
                this.dispose();
            } catch (Exception e) {
                System.out.println(e);
                
            }
        }
    }//GEN-LAST:event_tbinstitucionMousePressed

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnmenuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmbaremoInstitucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmbaremoInstitucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmbaremoInstitucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmbaremoInstitucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmbaremoInstitucion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnmenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblparametro;
    private java.awt.Panel panel2;
    public static javax.swing.JTable tbinstitucion;
    // End of variables declaration//GEN-END:variables
}
