/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTAS;

import DATOS.vcontrol;
import LOGICA.fcontrol;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class frmcontrol extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmcontrol
     */
    public frmcontrol() {
        initComponents();
        mostrarnumero();
    }
    

        private void mostrarnumero (){
        try {
            DefaultTableModel modelo;
            fcontrol func= new fcontrol();
            modelo=func.numeroControl();
            txtnumero.setText(modelo.getValueAt(0, 0).toString());
            txtfactura.setText(modelo.getValueAt(0, 1).toString());
            
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
            
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtnumero = new javax.swing.JTextField();
        lblcontrol = new javax.swing.JLabel();
        txtfactura = new javax.swing.JTextField();
        lblcontrol2 = new javax.swing.JLabel();
        panel2 = new java.awt.Panel();
        btnmodificar = new javax.swing.JButton();
        btnmenu = new javax.swing.JButton();
        lblcontrol1 = new javax.swing.JLabel();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("NUMERO DE CONTROL");
        setMaximumSize(new java.awt.Dimension(270, 170));
        setMinimumSize(new java.awt.Dimension(270, 170));
        setPreferredSize(new java.awt.Dimension(270, 170));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONTROL DE FACTURACION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.setLayout(null);

        txtnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumeroActionPerformed(evt);
            }
        });
        txtnumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnumeroKeyPressed(evt);
            }
        });
        jPanel1.add(txtnumero);
        txtnumero.setBounds(70, 20, 130, 30);

        lblcontrol.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcontrol.setText("CONTROL");
        jPanel1.add(lblcontrol);
        lblcontrol.setBounds(10, 20, 80, 30);

        txtfactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfacturaActionPerformed(evt);
            }
        });
        txtfactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfacturaKeyPressed(evt);
            }
        });
        jPanel1.add(txtfactura);
        txtfactura.setBounds(70, 60, 130, 30);

        lblcontrol2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcontrol2.setText("FACTURA");
        jPanel1.add(lblcontrol2);
        lblcontrol2.setBounds(10, 60, 60, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 50, 260, 100);

        panel2.setBackground(new java.awt.Color(0, 102, 153));
        panel2.setLayout(null);

        btnmodificar.setBackground(new java.awt.Color(255, 255, 255));
        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/archivo-nuevo.png"))); // NOI18N
        btnmodificar.setToolTipText("MODIFICAR REGISTRO");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        panel2.add(btnmodificar);
        btnmodificar.setBounds(0, 0, 60, 50);

        btnmenu.setBackground(new java.awt.Color(255, 255, 255));
        btnmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/salida.png"))); // NOI18N
        btnmenu.setText("MENU");
        btnmenu.setToolTipText("IR A MENU");
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });
        panel2.add(btnmenu);
        btnmenu.setBounds(140, 0, 110, 50);

        lblcontrol1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcontrol1.setText("NUMERO ");
        panel2.add(lblcontrol1);
        lblcontrol1.setBounds(10, 30, 160, 120);

        getContentPane().add(panel2);
        panel2.setBounds(0, 0, 290, 50);

        btnnuevo.setText("nuevo");
        btnnuevo.setToolTipText("NUEVO REGISTRO");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnnuevo);
        btnnuevo.setBounds(300, 0, 80, 30);

        btnguardar.setText("guardar");
        btnguardar.setToolTipText("GUARDAR REGISTRO");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar);
        btnguardar.setBounds(300, 30, 80, 30);

        btncancelar.setText("cancelar");
        btncancelar.setToolTipText("CANCELAR REGISTRO");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btncancelar);
        btncancelar.setBounds(300, 60, 80, 30);

        btnbuscar.setText("buscar");
        btnbuscar.setToolTipText("IR A MENU");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnbuscar);
        btnbuscar.setBounds(300, 90, 80, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumeroActionPerformed
        txtnumero.grabFocus();
    }//GEN-LAST:event_txtnumeroActionPerformed

    private void txtnumeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumeroKeyPressed

    }//GEN-LAST:event_txtnumeroKeyPressed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed

    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        if (txtnumero.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un Codigo para la Institucion.");
            txtnumero.requestFocus();
            return;
        }
        try {
            vcontrol dts= new vcontrol();
            fcontrol func=new fcontrol();

            dts.setNumeroControl(Integer.parseInt(txtnumero.getText()));
            func.insertar(dts);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "Error al guardar el registro.");
            JOptionPane.showConfirmDialog(rootPane, e);
        }

        

    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        if (txtnumero.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes un numero de control.");
            txtnumero.requestFocus();
            return;
        }
        if (txtfactura.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un numero de factura.");
            txtfactura.requestFocus();
            return;
        }
        try {
                vcontrol dts= new vcontrol();
                fcontrol func=new fcontrol();

                dts.setNumeroControl(Long.parseLong(txtnumero.getText()));
                dts.setFactura(Integer.parseInt(txtfactura.getText()));
                System.out.println((txtnumero.getText()));
                func.modificar(dts);
                mostrarnumero();
                JOptionPane.showMessageDialog(rootPane, "Registro modificado exitosamente.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error al modificar el registro.");
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
        
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnmenuActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnbuscarActionPerformed

    private void txtfacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfacturaActionPerformed

    private void txtfacturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfacturaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfacturaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmcontrol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmcontrol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmcontrol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmcontrol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmcontrol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmenu;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblcontrol;
    private javax.swing.JLabel lblcontrol1;
    private javax.swing.JLabel lblcontrol2;
    private java.awt.Panel panel2;
    private javax.swing.JTextField txtfactura;
    private javax.swing.JTextField txtnumero;
    // End of variables declaration//GEN-END:variables
}
