/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTAS;

import DATOS.vcategoria;
import LOGICA.fcategoria;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class frmcategoria extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmcategoria
     */
    public frmcategoria() {
        initComponents();
        inhabilitar();
    }
    
    

    
   private void inhabilitar (){
       //deshabilitar cajas de texto
        txtcodigoCategoria.setEnabled(false);
        txtnombreCategoria.setEnabled(false);

        

        //deshabilitar botones
        btnguardar.setEnabled(false);
        btneliminar.setEnabled(false);
        btnmodificar.setEnabled(false);
        btncancelar.setEnabled(false);
        
    }
   
    void vaciarCajas(){
         //vaciar cajas de texto
        txtcodigoCategoria.setText("");
        txtnombreCategoria.setText("");
    }
   
    void habilitar (){
        //habilitar cajas de texto
        txtcodigoCategoria.setEnabled(true);
        txtnombreCategoria.setEnabled(true);
        //habilitar botones
        btnguardar.setEnabled(true);
        btnmenu.setEnabled(true);
        btneliminar.setEnabled(true);

    }
  
private void nuevoCodigo(){
        try {
            int codigo=0;
           fcategoria funcion= new fcategoria();
           codigo=funcion.asignarCodigoCategoria();
           codigo=codigo+1; 
           txtcodigoCategoria.setText(String.valueOf(codigo));
           System.out.println(codigo);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "Error al cargar el nuevo codigo");
            JOptionPane.showConfirmDialog(rootPane, e);
        }
       
   }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new java.awt.Panel();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnmenu = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblcodigo = new javax.swing.JLabel();
        txtcodigoCategoria = new javax.swing.JTextField();
        txtnombreCategoria = new javax.swing.JTextField();
        lblnombre = new javax.swing.JLabel();
        btnhabilitar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CATEGORIAS DE ESTUDIOS");
        setMaximumSize(new java.awt.Dimension(620, 200));
        setMinimumSize(new java.awt.Dimension(620, 200));
        setPreferredSize(new java.awt.Dimension(620, 200));
        getContentPane().setLayout(null);

        panel2.setBackground(new java.awt.Color(0, 102, 153));
        panel2.setLayout(null);

        btnnuevo.setBackground(new java.awt.Color(255, 255, 255));
        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/agregar-documento-simbolo-delineado.png"))); // NOI18N
        btnnuevo.setToolTipText("NUEVO REGISTRO");
        btnnuevo.setNextFocusableComponent(txtcodigoCategoria);
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        panel2.add(btnnuevo);
        btnnuevo.setBounds(0, 0, 60, 50);

        btnguardar.setBackground(new java.awt.Color(255, 255, 255));
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/guardar.png"))); // NOI18N
        btnguardar.setToolTipText("GUARDAR REGISTRO");
        btnguardar.setNextFocusableComponent(btnmodificar);
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        panel2.add(btnguardar);
        btnguardar.setBounds(60, 0, 60, 50);

        btnmodificar.setBackground(new java.awt.Color(255, 255, 255));
        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/archivo-nuevo.png"))); // NOI18N
        btnmodificar.setToolTipText("MODIFICAR REGISTRO");
        btnmodificar.setNextFocusableComponent(btncancelar);
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        panel2.add(btnmodificar);
        btnmodificar.setBounds(120, 0, 60, 50);

        btncancelar.setBackground(new java.awt.Color(255, 255, 255));
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/expediente.png"))); // NOI18N
        btncancelar.setToolTipText("CANCELAR REGISTRO");
        btncancelar.setNextFocusableComponent(btneliminar);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        panel2.add(btncancelar);
        btncancelar.setBounds(180, 0, 60, 50);

        btneliminar.setBackground(new java.awt.Color(255, 255, 255));
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/cubo-de-basura.png"))); // NOI18N
        btneliminar.setToolTipText("ELIMINAR REGISTRO");
        btneliminar.setNextFocusableComponent(btnbuscar);
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        panel2.add(btneliminar);
        btneliminar.setBounds(240, 0, 60, 50);

        btnmenu.setBackground(new java.awt.Color(255, 255, 255));
        btnmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/salida.png"))); // NOI18N
        btnmenu.setText("MENU");
        btnmenu.setToolTipText("IR A MENU");
        btnmenu.setNextFocusableComponent(txtcodigoCategoria);
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });
        panel2.add(btnmenu);
        btnmenu.setBounds(487, 0, 110, 50);

        btnbuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/buscar.png"))); // NOI18N
        btnbuscar.setToolTipText("IR A MENU");
        btnbuscar.setNextFocusableComponent(btnmenu);
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        panel2.add(btnbuscar);
        btnbuscar.setBounds(300, 0, 60, 50);

        getContentPane().add(panel2);
        panel2.setBounds(0, 0, 600, 50);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DETALLE DE CATEGORIA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.setLayout(null);

        lblcodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcodigo.setText("CODIGO ");
        jPanel1.add(lblcodigo);
        lblcodigo.setBounds(10, 20, 60, 30);

        txtcodigoCategoria.setNextFocusableComponent(txtnombreCategoria);
        txtcodigoCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoCategoriaActionPerformed(evt);
            }
        });
        txtcodigoCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcodigoCategoriaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcodigoCategoriaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodigoCategoriaKeyTyped(evt);
            }
        });
        jPanel1.add(txtcodigoCategoria);
        txtcodigoCategoria.setBounds(90, 20, 120, 30);

        txtnombreCategoria.setNextFocusableComponent(btnguardar);
        txtnombreCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreCategoriaActionPerformed(evt);
            }
        });
        txtnombreCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnombreCategoriaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnombreCategoriaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreCategoriaKeyTyped(evt);
            }
        });
        jPanel1.add(txtnombreCategoria);
        txtnombreCategoria.setBounds(90, 60, 490, 30);

        lblnombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblnombre.setText("NOMBRE");
        jPanel1.add(lblnombre);
        lblnombre.setBounds(10, 60, 60, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 50, 600, 110);

        btnhabilitar.setText("habilitar");
        btnhabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhabilitarActionPerformed(evt);
            }
        });
        getContentPane().add(btnhabilitar);
        btnhabilitar.setBounds(660, 70, 71, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed

        habilitar();
        vaciarCajas();
        txtcodigoCategoria.requestFocus();
        btnmodificar.setEnabled(false);
        btnmenu.setEnabled(false);
        btnnuevo.setEnabled(false);
        btneliminar.setEnabled(false);
        btncancelar.setEnabled(true);
        btnguardar.setEnabled(true);
        nuevoCodigo();
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        if (txtcodigoCategoria.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un Codigo para la categoria");
            txtcodigoCategoria.requestFocus();
            return;
        }
        if (txtnombreCategoria.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un Nombre para la categoria");
            txtnombreCategoria.requestFocus();
            return;
        }

        try {
            vcategoria dts= new vcategoria();
            fcategoria func=new fcategoria();

            dts.setCodigoCategoria(Integer.parseInt(txtcodigoCategoria.getText()));
            dts.setNombreCategoria(txtnombreCategoria.getText());

            boolean resultado = func.insertar(dts);
            if (resultado==true){   
                JOptionPane.showMessageDialog(rootPane, "Se ha almacenado el registro exitosamente");
                //mostrar("");
                inhabilitar();
                //habilitar botones
                btnmenu.setEnabled(true);
                btnnuevo.setEnabled(true);
                //ihabilitar botones
                btnguardar.setEnabled(false);
            }
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error al intentar guardar el registro");
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        if (txtcodigoCategoria.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un Codigo para la categoria");
            txtcodigoCategoria.requestFocus();
            return;
        }

        if (txtnombreCategoria.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un Nombre para la categoria");
            txtnombreCategoria.requestFocus();
            return;
        }

        try {
            vcategoria dts= new vcategoria();
            fcategoria func=new fcategoria();

            dts.setCodigoCategoria(Integer.parseInt(txtcodigoCategoria.getText()));
            dts.setNombreCategoria(txtnombreCategoria.getText());
            boolean resultado=func.modificar(dts);
            if(resultado==true){
                inhabilitar();
                btnmenu.setEnabled(true);
                JOptionPane.showMessageDialog(rootPane, "Se modifico el registro exitosamente.");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error al intentar modificar el registro.");
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
       
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Se ha cancelado la Operacion.");
        inhabilitar ();
        btnmenu.setEnabled(true);
        btnnuevo.setEnabled(true);
        vaciarCajas();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        if (!txtcodigoCategoria.getText().equals("")) {

            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Seguro que quiere eliminar este registro?", "Confirmar", 2);

            if (confirmacion==0) {
                
                try {
                    fcategoria func= new fcategoria();
                    vcategoria dts= new vcategoria ();

                    dts.setCodigoCategoria(Integer.parseInt(txtcodigoCategoria.getText()));
                    func.eliminar(dts);
                    //mostrar("");
                    inhabilitar ();
                    btnmenu.setEnabled(true);
                    vaciarCajas();
                    JOptionPane.showMessageDialog(rootPane, "Se ha elimniado el registro.");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Error al intentar eliminar el registro.");
                    JOptionPane.showMessageDialog(rootPane, e);
                }
                
            }
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnmenuActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        try {
            frmconsultaCategoria form= new  frmconsultaCategoria();
            form.toFront();
            frmmenu.escritorio.add(form);
            form.setSize(740, 540);
            form.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error al intentar abrir el formulario de consulta de categoria.");
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void txtcodigoCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoCategoriaActionPerformed
        // TODO add your handling code here:
        txtnombreCategoria.grabFocus();
    }//GEN-LAST:event_txtcodigoCategoriaActionPerformed

    private void txtcodigoCategoriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoCategoriaKeyPressed

    }//GEN-LAST:event_txtcodigoCategoriaKeyPressed

    private void txtcodigoCategoriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoCategoriaKeyReleased

    }//GEN-LAST:event_txtcodigoCategoriaKeyReleased

    private void txtnombreCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreCategoriaActionPerformed

    private void txtnombreCategoriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreCategoriaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreCategoriaKeyPressed

    private void txtnombreCategoriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreCategoriaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreCategoriaKeyReleased

    private void btnhabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhabilitarActionPerformed
        // TODO add your handling code here:
        habilitar();
        btnguardar.setEnabled(false);
        btncancelar.setEnabled(true);
        btnmodificar.setEnabled(true);
        btnmenu.setEnabled(false);
    }//GEN-LAST:event_btnhabilitarActionPerformed

    private void txtcodigoCategoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoCategoriaKeyTyped
        
        Character c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }
    }//GEN-LAST:event_txtcodigoCategoriaKeyTyped

    private void txtnombreCategoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreCategoriaKeyTyped
        Character c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }
    }//GEN-LAST:event_txtnombreCategoriaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmcategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmcategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmcategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmcategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmcategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    public static javax.swing.JButton btnhabilitar;
    private javax.swing.JButton btnmenu;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JLabel lblnombre;
    private java.awt.Panel panel2;
    public static javax.swing.JTextField txtcodigoCategoria;
    public static javax.swing.JTextField txtnombreCategoria;
    // End of variables declaration//GEN-END:variables
}
