/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTAS;

import LOGICA.conexion;
import LOGICA.finstitucion;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author user
 */
public class frmconsultaInstitucion extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmconsultaInstitucion
     */
    public frmconsultaInstitucion() {
        initComponents();
       mostrar(cbparametro.getSelectedItem().toString(),"");
       sizetable();
    }

    //Carga en una tabla los resutlados de la busqueda en instituciones
    private void mostrar (String parametro,String buscar){
        try {
            DefaultTableModel modelo;
            String valor;
            String valorfinal;
            valorfinal="";
            valor= cbparametro.getSelectedItem().toString();
            if (valor=="NOMBRE"){
                valorfinal="nombreInstitucion";
            }
            if (valor=="CODIGO"){
                valorfinal="codigoInstitucion";
            }
            if (valor=="CONTACTO"){
                valorfinal="contactoOrganizacion";
            }
            if (valor=="RIF"){
                valorfinal="rif";
            }
            System.out.println(cbparametro.getSelectedItem().toString());
            finstitucion func= new finstitucion();
            modelo=func.mostrarInstitucion2(valorfinal,buscar);
            tbinstitucion.setModel(modelo);
            lblTotal.setText(""+ Integer.toString(func.totalRegistros));   
            sizetable();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "Error al cargar los registros en la tabla");
            JOptionPane.showConfirmDialog(rootPane, e);

        }

    }
    
        
    private void sizetable(){
        
        try {
            TableColumnModel columnModel = tbinstitucion.getColumnModel();
            columnModel.getColumn(0).setPreferredWidth(150);
            columnModel.getColumn(0).setMaxWidth(150);
            columnModel.getColumn(1).setPreferredWidth(800);
            columnModel.getColumn(1).setMaxWidth(800);
            columnModel.getColumn(2).setPreferredWidth(400);
            columnModel.getColumn(2).setMaxWidth(400);
            columnModel.getColumn(3).setPreferredWidth(800);
            columnModel.getColumn(3).setMaxWidth(800);
            columnModel.getColumn(4).setPreferredWidth(0);
            columnModel.getColumn(4).setMaxWidth(0);
            columnModel.getColumn(5).setPreferredWidth(0);
            columnModel.getColumn(5).setMaxWidth(0);
            columnModel.getColumn(6).setPreferredWidth(0);
            columnModel.getColumn(6).setMaxWidth(0);
            columnModel.getColumn(7).setPreferredWidth(0);
            columnModel.getColumn(7).setMaxWidth(0);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "Error al ajustar la tabla");
            JOptionPane.showConfirmDialog(rootPane, e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbinstitucion = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        panel2 = new java.awt.Panel();
        btnmenu = new javax.swing.JButton();
        lblparametro = new javax.swing.JLabel();
        cbparametro = new javax.swing.JComboBox();
        btnreporte = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        btntodos = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CONSULTA DE INSTITUCION");
        setMaximumSize(new java.awt.Dimension(830, 555));
        setMinimumSize(new java.awt.Dimension(830, 555));
        setPreferredSize(new java.awt.Dimension(830, 555));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONSULTA DE INSTITUCION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(960, 450));
        jPanel1.setMinimumSize(new java.awt.Dimension(960, 450));
        jPanel1.setLayout(null);

        tbinstitucion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "CODIGO", "NOMBRE"
            }
        ));
        tbinstitucion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbinstitucionMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbinstitucionMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(tbinstitucion);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(10, 30, 790, 360);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("TOTAL DE REGISTROS:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(520, 390, 140, 30);

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 0, 0));
        lblTotal.setText("0");
        jPanel1.add(lblTotal);
        lblTotal.setBounds(670, 390, 90, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 80, 810, 420);

        panel2.setBackground(new java.awt.Color(0, 102, 153));
        panel2.setLayout(null);

        btnmenu.setBackground(new java.awt.Color(255, 255, 255));
        btnmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/salida.png"))); // NOI18N
        btnmenu.setText("MENU");
        btnmenu.setToolTipText("IR A MENU");
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });
        panel2.add(btnmenu);
        btnmenu.setBounds(700, 0, 110, 50);

        lblparametro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblparametro.setForeground(new java.awt.Color(255, 255, 255));
        lblparametro.setText("PARAMETRO DE BUSQUEDA");
        panel2.add(lblparametro);
        lblparametro.setBounds(10, 20, 180, 30);

        cbparametro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NOMBRE", "CODIGO", "CONTACTO", "RIF" }));
        cbparametro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbparametroActionPerformed(evt);
            }
        });
        panel2.add(cbparametro);
        cbparametro.setBounds(190, 20, 290, 30);

        btnreporte.setBackground(new java.awt.Color(255, 255, 255));
        btnreporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/impresora-3.png"))); // NOI18N
        btnreporte.setToolTipText("IMPRIMIR REPORTE");
        btnreporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreporteActionPerformed(evt);
            }
        });
        panel2.add(btnreporte);
        btnreporte.setBounds(490, 0, 70, 50);

        btnbuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/buscar.png"))); // NOI18N
        btnbuscar.setToolTipText("BUSCAR REGISTRO");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        panel2.add(btnbuscar);
        btnbuscar.setBounds(560, 0, 70, 50);

        btntodos.setBackground(new java.awt.Color(255, 255, 255));
        btntodos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/equipo.png"))); // NOI18N
        btntodos.setToolTipText("MOSTRAR TODOS LOS REGISTROS");
        btntodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntodosActionPerformed(evt);
            }
        });
        panel2.add(btntodos);
        btntodos.setBounds(630, 0, 70, 50);

        getContentPane().add(panel2);
        panel2.setBounds(0, 0, 1000, 50);

        txtbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtbuscarMousePressed(evt);
            }
        });
        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscarKeyTyped(evt);
            }
        });
        getContentPane().add(txtbuscar);
        txtbuscar.setBounds(10, 50, 790, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbinstitucionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbinstitucionMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tbinstitucionMouseClicked

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnmenuActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        String dato="";
        dato=txtbuscar.getText();
        mostrar(cbparametro.getSelectedItem().toString(),dato);
        
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void txtbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyPressed

    }//GEN-LAST:event_txtbuscarKeyPressed

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased

    }//GEN-LAST:event_txtbuscarKeyReleased

    private void btntodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntodosActionPerformed
        // TODO add your handling code here:
        txtbuscar.setText("");
        String dato="";
        dato=txtbuscar.getText();
        mostrar(cbparametro.getSelectedItem().toString(),dato);   
    }//GEN-LAST:event_btntodosActionPerformed

    private void cbparametroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbparametroActionPerformed
        // TODO add your handling code here:
        
    mostrar("","");
        System.out.println(cbparametro.getSelectedItem().toString());
    }//GEN-LAST:event_cbparametroActionPerformed

    private void txtbuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbuscarMousePressed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_txtbuscarMousePressed
   

    private void tbinstitucionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbinstitucionMousePressed
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            //habilar los elementos para su modificacion

            try {
                int fila = tbinstitucion.rowAtPoint(evt.getPoint());
                frminstitucion.txtcodigoInstitucion.setText(tbinstitucion.getValueAt(fila, 0).toString());
                frminstitucion.txtnombreInstitucion.setText(tbinstitucion.getValueAt(fila, 1).toString());
                frminstitucion.txtcargoContacto.setText(tbinstitucion.getValueAt(fila, 2).toString());
                frminstitucion.txttelefono.setText(tbinstitucion.getValueAt(fila, 3).toString());
                frminstitucion.txtdireccion.setText(tbinstitucion.getValueAt(fila, 4).toString());
                frminstitucion.txtcontactoOrganizacion.setText(tbinstitucion.getValueAt(fila, 5).toString());
                frminstitucion.txtrif.setText(tbinstitucion.getValueAt(fila, 6).toString());
                frminstitucion.txttelefonoContacto.setText(tbinstitucion.getValueAt(fila, 7).toString());
                frminstitucion.btnhabilitar.doClick();
                this.dispose();
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_tbinstitucionMousePressed

    private Connection connection= new conexion().conectar();
    private void btnreporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreporteActionPerformed
        Map p= new HashMap();
        JasperReport report;
        JasperPrint print;
        
        try {
            report=JasperCompileManager.compileReport(new File("").getAbsolutePath()+
            "/src/REPORTES/rptInstituciones.jrxml");
            
            print=JasperFillManager.fillReport(report, p,connection);
            JasperViewer view= new JasperViewer(print, false);
            view.setTitle("Reporte de Instituciones");
            view.setVisible(true);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnreporteActionPerformed

    private void txtbuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyTyped
        Character c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }
    }//GEN-LAST:event_txtbuscarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmconsultaInstitucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmconsultaInstitucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmconsultaInstitucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmconsultaInstitucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmconsultaInstitucion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnmenu;
    private javax.swing.JButton btnreporte;
    private javax.swing.JButton btntodos;
    private javax.swing.JComboBox cbparametro;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblparametro;
    private java.awt.Panel panel2;
    public static javax.swing.JTable tbinstitucion;
    public static javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
