/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTAS;

import DATOS.vdetalleSolicitud;
import DATOS.vestudio;
import DATOS.vestudiosInstitucion;
import LOGICA.fcategoria;
import LOGICA.fdetalleSolicitud;
import LOGICA.festudio;
import LOGICA.festudiosInstitucion;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class frmestudiosInstitucion extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmestudiosInstitucion
     */
    public frmestudiosInstitucion() {
        initComponents();
        comboCategoria("categoriaestudios","nombreCategoria");
    }

    
    private void mostrar (String codigoInstitucion,String codigoCategoria){
        try {
            DefaultTableModel modelo;
            String valor;
            String valorfinal,categoria="";
            valorfinal="";
            categoria=txtcodigoCategoria.getText();
            
            festudiosInstitucion func= new festudiosInstitucion();
            modelo=func.mostrarEstudio2(codigoInstitucion,categoria);
            tbestudios.setModel(modelo);
            lblTotal.setText(""+ Integer.toString(func.totalRegistros));   
            ocultarColumnas();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);

        }
 }
    
    private void ocultarColumnas(){
        tbestudios.getColumnModel().getColumn(0).setPreferredWidth(100);
        tbestudios.getColumnModel().getColumn(0).setMaxWidth(100);
        tbestudios.getColumnModel().getColumn(0).setMinWidth(100);
        tbestudios.getColumnModel().getColumn(1).setPreferredWidth(0);
        tbestudios.getColumnModel().getColumn(1).setMaxWidth(0);
        tbestudios.getColumnModel().getColumn(1).setMinWidth(0);
        tbestudios.getColumnModel().getColumn(2).setPreferredWidth(0);
        tbestudios.getColumnModel().getColumn(2).setMaxWidth(0);
        tbestudios.getColumnModel().getColumn(2).setMinWidth(0);
        tbestudios.getColumnModel().getColumn(3).setPreferredWidth(500);
        tbestudios.getColumnModel().getColumn(3).setMaxWidth(500);
        tbestudios.getColumnModel().getColumn(3).setMinWidth(500);
        tbestudios.getColumnModel().getColumn(4).setPreferredWidth(300);
        tbestudios.getColumnModel().getColumn(4).setMaxWidth(300);
        tbestudios.getColumnModel().getColumn(4).setMinWidth(300);
        tbestudios.getColumnModel().getColumn(5).setPreferredWidth(0);
        tbestudios.getColumnModel().getColumn(5).setMaxWidth(0);
        tbestudios.getColumnModel().getColumn(5).setMinWidth(0);
    }
        private void mostrarEstudiofrmSolicitud (String numeroSolicitud){
        try {
            DefaultTableModel modelo;
            String valor;
            String valorfinal,categoria="";
            valorfinal="";
            categoria=txtcodigoCategoria.getText();
            
            fdetalleSolicitud func= new fdetalleSolicitud();
            modelo=func.mostrarEstudioSolicitado(numeroSolicitud);
            frmsolicitud.tbestudiosSolicitados.setModel(modelo);
            frmsolicitud.lbltotalFactura.setText(func.totalFactura.toString());
 
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);

        }
 }
    
void comboCategoria(String tabla, String nombrecol){
        festudio func= new festudio();
        Object[] nombre = func.comboCategoria(tabla,nombrecol);
        cbcategoria.removeAllItems();
        for(int i=0;i<nombre.length;i++){
        cbcategoria.addItem(nombre[i]);  
        
        }
        
   }

     void cargarCategoria (String nombre){
         try {
            DefaultTableModel modelo;
            festudio func= new festudio();
            vestudio dts= new vestudio();
            dts.setNombreEstudio(nombre);
            modelo=func.cargaCategoria(dts.getNombreEstudio());
            txtcodigoCategoria.setText(modelo.getValueAt(0,0).toString());
            ocultarColumnas();
        } catch (Exception e) {
           // JOptionPane.showConfirmDialog(rootPane, e);
            
        }
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbestudios = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cbcategoria = new javax.swing.JComboBox();
        btnmenu = new javax.swing.JButton();
        txtcodigoInstitucion = new javax.swing.JTextField();
        lblparametro2 = new javax.swing.JLabel();
        txtnombreInstitucion = new javax.swing.JTextField();
        lblparametro = new javax.swing.JLabel();
        lblparametro1 = new javax.swing.JLabel();
        txtcodigoCategoria = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        txtnumeroSolicitud = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ESTUDIOS DE INSTITUCION");
        setMaximumSize(new java.awt.Dimension(760, 540));
        setMinimumSize(new java.awt.Dimension(760, 540));
        setPreferredSize(new java.awt.Dimension(760, 540));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DETALLE DE ESTUDIOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(960, 450));
        jPanel1.setMinimumSize(new java.awt.Dimension(960, 450));
        jPanel1.setLayout(null);

        tbestudios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "CODIGO", "NOMBRE"
            }
        ));
        tbestudios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbestudiosMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbestudiosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbestudios);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(10, 30, 720, 360);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("TOTAL DE REGISTROS:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(490, 390, 140, 30);

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 0, 0));
        lblTotal.setText("0");
        jPanel1.add(lblTotal);
        lblTotal.setBounds(640, 390, 90, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 80, 740, 420);

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        cbcategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NOMBRE", "CODIGO" }));
        cbcategoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbcategoriaItemStateChanged(evt);
            }
        });
        cbcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcategoriaActionPerformed(evt);
            }
        });
        jPanel2.add(cbcategoria);
        cbcategoria.setBounds(120, 50, 600, 30);

        btnmenu.setBackground(new java.awt.Color(255, 255, 255));
        btnmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/salida.png"))); // NOI18N
        btnmenu.setText("MENU");
        btnmenu.setToolTipText("IR A MENU");
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });
        jPanel2.add(btnmenu);
        btnmenu.setBounds(610, 0, 110, 50);

        txtcodigoInstitucion.setEnabled(false);
        txtcodigoInstitucion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtcodigoInstitucionMousePressed(evt);
            }
        });
        txtcodigoInstitucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoInstitucionActionPerformed(evt);
            }
        });
        txtcodigoInstitucion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcodigoInstitucionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcodigoInstitucionKeyReleased(evt);
            }
        });
        jPanel2.add(txtcodigoInstitucion);
        txtcodigoInstitucion.setBounds(480, 10, 100, 30);

        lblparametro2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblparametro2.setForeground(new java.awt.Color(255, 255, 255));
        lblparametro2.setText("CODIGO");
        jPanel2.add(lblparametro2);
        lblparametro2.setBounds(430, 10, 50, 30);

        txtnombreInstitucion.setEnabled(false);
        txtnombreInstitucion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtnombreInstitucionMousePressed(evt);
            }
        });
        txtnombreInstitucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreInstitucionActionPerformed(evt);
            }
        });
        txtnombreInstitucion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnombreInstitucionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnombreInstitucionKeyReleased(evt);
            }
        });
        jPanel2.add(txtnombreInstitucion);
        txtnombreInstitucion.setBounds(120, 10, 310, 30);

        lblparametro.setBackground(new java.awt.Color(255, 255, 255));
        lblparametro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblparametro.setForeground(new java.awt.Color(255, 255, 255));
        lblparametro.setText("INSTITUCION");
        jPanel2.add(lblparametro);
        lblparametro.setBounds(10, 10, 110, 30);

        lblparametro1.setBackground(new java.awt.Color(255, 255, 255));
        lblparametro1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblparametro1.setForeground(new java.awt.Color(255, 255, 255));
        lblparametro1.setText("CATEGORIA");
        jPanel2.add(lblparametro1);
        lblparametro1.setBounds(10, 50, 90, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 870, 80);

        txtcodigoCategoria.setText(" ");
        getContentPane().add(txtcodigoCategoria);
        txtcodigoCategoria.setBounds(880, 90, 60, 30);

        btnbuscar.setText("BUSCAR");
        btnbuscar.setToolTipText("IR A MENU");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnbuscar);
        btnbuscar.setBounds(880, 20, 90, 30);

        txtnumeroSolicitud.setText(" ");
        getContentPane().add(txtnumeroSolicitud);
        txtnumeroSolicitud.setBounds(880, 50, 60, 30);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(960, 60, 34, 14);

        jLabel2.setText("codigoCategoria");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(960, 100, 80, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbestudiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbestudiosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbestudiosMouseClicked

    private void tbestudiosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbestudiosMousePressed
        // TODO add your handling code here:
        if (evt.getClickCount()==2){
            
            try {
                //habilar los elementos para su modificacion
                fdetalleSolicitud funcion = new fdetalleSolicitud();
                vdetalleSolicitud dts = new vdetalleSolicitud();

                int fila = tbestudios.rowAtPoint(evt.getPoint());

                dts.setNumeroSolicitud(Integer.parseInt(txtnumeroSolicitud.getText()));
                dts.setNumeroEstudio(Integer.parseInt(tbestudios.getValueAt(fila, 0).toString()));

                funcion.insertar(dts);
                mostrarEstudiofrmSolicitud(txtnumeroSolicitud.getText());
                frmsolicitud.sizetable();
                JOptionPane.showMessageDialog(rootPane, "Estudio Agregado.");
            } catch (Exception e) {
                
            }
            

        }
    }//GEN-LAST:event_tbestudiosMousePressed

    private void cbcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcategoriaActionPerformed
        // TODO add your handling code here:
            Object dato =(String)cbcategoria.getSelectedItem();
            String nombre= String.valueOf(dato);
            cargarCategoria(nombre);
        String categoria,codigoInstitucion="";
        codigoInstitucion=txtcodigoInstitucion.getText();
        categoria=txtcodigoCategoria.getText();
        mostrar(codigoInstitucion,categoria);
        ocultarColumnas();
    }//GEN-LAST:event_cbcategoriaActionPerformed

    private void txtnombreInstitucionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnombreInstitucionMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreInstitucionMousePressed

    private void txtnombreInstitucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreInstitucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreInstitucionActionPerformed

    private void txtnombreInstitucionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreInstitucionKeyPressed

    }//GEN-LAST:event_txtnombreInstitucionKeyPressed

    private void txtnombreInstitucionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreInstitucionKeyReleased

    }//GEN-LAST:event_txtnombreInstitucionKeyReleased

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        String codigoInstitucion,categoria="";
        codigoInstitucion=txtcodigoInstitucion.getText();
        categoria=txtcodigoCategoria.getText();
        mostrar(codigoInstitucion,categoria);
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void txtcodigoInstitucionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcodigoInstitucionMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoInstitucionMousePressed

    private void txtcodigoInstitucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoInstitucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoInstitucionActionPerformed

    private void txtcodigoInstitucionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoInstitucionKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoInstitucionKeyPressed

    private void txtcodigoInstitucionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoInstitucionKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoInstitucionKeyReleased

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnmenuActionPerformed

    private void cbcategoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbcategoriaItemStateChanged
        
    }//GEN-LAST:event_cbcategoriaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmestudiosInstitucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmestudiosInstitucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmestudiosInstitucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmestudiosInstitucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmestudiosInstitucion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnmenu;
    private javax.swing.JComboBox cbcategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblparametro;
    private javax.swing.JLabel lblparametro1;
    private javax.swing.JLabel lblparametro2;
    public static javax.swing.JTable tbestudios;
    public static javax.swing.JTextField txtcodigoCategoria;
    public static javax.swing.JTextField txtcodigoInstitucion;
    public static javax.swing.JTextField txtnombreInstitucion;
    public static javax.swing.JTextField txtnumeroSolicitud;
    // End of variables declaration//GEN-END:variables
}
