/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTAS;

import DATOS.vimpresora;
import LOGICA.fimpresora;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author user
 */
public class frmimpresora extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmimpresora
     */
    public frmimpresora() {
        initComponents();
        mostrar("");
        inhabilitar();
    }
      void inhabilitar (){
        txtnombreImpresora.setEnabled(false);
        txtdireccion.setEnabled(false);
        txtcodigoImpresora.setEnabled(false);
          
        //deshabilitar botones
        btnguardar.setEnabled(false);
        btneliminar.setEnabled(false);
        btnmodificar.setEnabled(false);
        btncancelar.setEnabled(false);
        
        //procedimiento limpiar cajas de texto
        limpiar();
        
    }
      
    private void sizetable(){
    TableColumnModel columnModel = tbimpresora.getColumnModel();
    columnModel.getColumn(0).setPreferredWidth(60);
    columnModel.getColumn(1).setPreferredWidth(150);
    columnModel.getColumn(2).setPreferredWidth(150);
    }

      void limpiar (){
          txtnombreImpresora.setText("");
          txtdireccion.setText("");
          txtcodigoImpresora.setText("");
      
      }
   
    void habilitar (){
          txtnombreImpresora.setEnabled(true);
          txtdireccion.setEnabled(true);
          txtcodigoImpresora.setEnabled(true);
          
          limpiar();
          
                  //deshabilitar botones
        btnguardar.setEnabled(true);
        btnmodificar.setEnabled(true);
        btncancelar.setEnabled(true);
        
    }
    
    
    void mostrar (String buscar){
        try {
            DefaultTableModel modelo;
            fimpresora func= new fimpresora();
            modelo=func.mostrarImpresora(buscar);
            tbimpresora.setModel(modelo);
   
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
            
        }
        
        sizetable();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new java.awt.Panel();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnmenu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblcodigo = new javax.swing.JLabel();
        txtcodigoImpresora = new javax.swing.JTextField();
        txtnombreImpresora = new javax.swing.JTextField();
        lblnombre = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        lblnombre1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbimpresora = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("IMPRESORA");
        setMaximumSize(new java.awt.Dimension(610, 340));
        setMinimumSize(new java.awt.Dimension(610, 340));
        setPreferredSize(new java.awt.Dimension(610, 340));
        getContentPane().setLayout(null);

        panel2.setBackground(new java.awt.Color(0, 102, 153));
        panel2.setLayout(null);

        btnnuevo.setBackground(new java.awt.Color(255, 255, 255));
        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/agregar-documento-simbolo-delineado.png"))); // NOI18N
        btnnuevo.setToolTipText("NUEVO REGISTRO");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        panel2.add(btnnuevo);
        btnnuevo.setBounds(0, 0, 50, 50);

        btnguardar.setBackground(new java.awt.Color(255, 255, 255));
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/guardar.png"))); // NOI18N
        btnguardar.setToolTipText("GUARDAR REGISTRO");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        panel2.add(btnguardar);
        btnguardar.setBounds(50, 0, 50, 50);

        btnmodificar.setBackground(new java.awt.Color(255, 255, 255));
        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/archivo-nuevo.png"))); // NOI18N
        btnmodificar.setToolTipText("MODIFICAR REGISTRO");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        panel2.add(btnmodificar);
        btnmodificar.setBounds(100, 0, 50, 50);

        btncancelar.setBackground(new java.awt.Color(255, 255, 255));
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/expediente.png"))); // NOI18N
        btncancelar.setToolTipText("CANCELAR REGISTRO");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        panel2.add(btncancelar);
        btncancelar.setBounds(150, 0, 50, 50);

        btneliminar.setBackground(new java.awt.Color(255, 255, 255));
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/cubo-de-basura.png"))); // NOI18N
        btneliminar.setToolTipText("ELIMINAR REGISTRO");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        panel2.add(btneliminar);
        btneliminar.setBounds(200, 0, 50, 50);

        btnmenu.setBackground(new java.awt.Color(255, 255, 255));
        btnmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/salida.png"))); // NOI18N
        btnmenu.setText("MENU");
        btnmenu.setToolTipText("IR A MENU");
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });
        panel2.add(btnmenu);
        btnmenu.setBounds(470, 0, 120, 50);

        getContentPane().add(panel2);
        panel2.setBounds(0, 0, 600, 50);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DETALLE DE IMPRESORAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.setLayout(null);

        lblcodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcodigo.setText("CODIGO ");
        jPanel1.add(lblcodigo);
        lblcodigo.setBounds(10, 20, 60, 30);

        txtcodigoImpresora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoImpresoraActionPerformed(evt);
            }
        });
        txtcodigoImpresora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcodigoImpresoraKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcodigoImpresoraKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodigoImpresoraKeyTyped(evt);
            }
        });
        jPanel1.add(txtcodigoImpresora);
        txtcodigoImpresora.setBounds(90, 20, 120, 30);

        txtnombreImpresora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreImpresoraActionPerformed(evt);
            }
        });
        txtnombreImpresora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnombreImpresoraKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnombreImpresoraKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreImpresoraKeyTyped(evt);
            }
        });
        jPanel1.add(txtnombreImpresora);
        txtnombreImpresora.setBounds(90, 60, 490, 30);

        lblnombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblnombre.setText("NOMBRE");
        jPanel1.add(lblnombre);
        lblnombre.setBounds(10, 60, 70, 30);

        txtdireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdireccionActionPerformed(evt);
            }
        });
        txtdireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdireccionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdireccionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdireccionKeyTyped(evt);
            }
        });
        jPanel1.add(txtdireccion);
        txtdireccion.setBounds(90, 100, 490, 30);

        lblnombre1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblnombre1.setText("DIRECCION");
        jPanel1.add(lblnombre1);
        lblnombre1.setBounds(10, 100, 70, 30);

        tbimpresora.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "CODIGO", "DIRECCION"
            }
        ));
        tbimpresora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbimpresoraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbimpresora);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 150, 570, 90);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 50, 590, 250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed

        habilitar();
        txtcodigoImpresora.requestFocus();
        btnmodificar.setEnabled(false);
        btnmenu.setEnabled(false);
        btnnuevo.setEnabled(false);
        btneliminar.setEnabled(false);
        btncancelar.setEnabled(true);
        btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        if (txtcodigoImpresora.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un Codigo para la Institucion");
            txtcodigoImpresora.requestFocus();
            return;
        }
        if (txtnombreImpresora.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un Nombre para la Institucion");
            txtnombreImpresora.requestFocus();
            return;
        }

        vimpresora dts= new vimpresora();
        fimpresora func=new fimpresora();

        dts.setCodigoImpresora(Integer.parseInt(txtcodigoImpresora.getText()));
        dts.setNombreImpresora(txtnombreImpresora.getText());
        dts.setDireccionImpresora(txtdireccion.getText());

        func.insertar(dts);
        mostrar("");
        inhabilitar();
        //habilitar botones
        btnmenu.setEnabled(true);
        btnnuevo.setEnabled(true);
        //ihabilitar botones
        btnguardar.setEnabled(false);

        //  sizetable();
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        if (txtcodigoImpresora.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un Codigo para la impresora");
            txtcodigoImpresora.requestFocus();
            return;
        }

        if (txtnombreImpresora.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un Nombre para la Impresora");
            txtnombreImpresora.requestFocus();
            return;
        }

        
        if (txtdireccion.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar una direccion para la impresora");
            txtdireccion.requestFocus();
            return;
        }
        vimpresora dts= new vimpresora();
        fimpresora func=new fimpresora();

        dts.setCodigoImpresora(Integer.parseInt(txtcodigoImpresora.getText()));
        dts.setNombreImpresora(txtnombreImpresora.getText());
        dts.setDireccionImpresora(txtdireccion.getText());
        func.modificar(dts);
        mostrar("");
        inhabilitar();
        btnmenu.setEnabled(true);
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        inhabilitar ();
        btnmenu.setEnabled(true);
        btnnuevo.setEnabled(true);
        //      mostrar("");
        //    sizetable();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        if (!txtcodigoImpresora.getText().equals("")) {

            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Seguro que quiere eliminar este registro?", "Confirmar", 2);

            if (confirmacion==0) {
                fimpresora func= new fimpresora();
                vimpresora dts= new vimpresora ();

                dts.setCodigoImpresora(Integer.parseInt(txtcodigoImpresora.getText()));
                func.eliminar(dts);
                //mostrar("");
                inhabilitar ();
                btnmenu.setEnabled(true);
                //sizetable();
            }
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnmenuActionPerformed

    private void txtcodigoImpresoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoImpresoraActionPerformed
        // TODO add your handling code here:
        txtnombreImpresora.grabFocus();
    }//GEN-LAST:event_txtcodigoImpresoraActionPerformed

    private void txtcodigoImpresoraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoImpresoraKeyPressed

    }//GEN-LAST:event_txtcodigoImpresoraKeyPressed

    private void txtcodigoImpresoraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoImpresoraKeyReleased

    }//GEN-LAST:event_txtcodigoImpresoraKeyReleased

    private void txtnombreImpresoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreImpresoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreImpresoraActionPerformed

    private void txtnombreImpresoraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreImpresoraKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreImpresoraKeyPressed

    private void txtnombreImpresoraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreImpresoraKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreImpresoraKeyReleased

    private void txtdireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionActionPerformed

    private void txtdireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionKeyPressed

    private void txtdireccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionKeyReleased

    private void tbimpresoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbimpresoraMouseClicked
        // TODO add your handling code here:
        //habilar los elementos para su modificacion
        btnmodificar.setEnabled(true);
        btneliminar.setEnabled(true);
        btncancelar.setEnabled(true);
        btnmenu.setEnabled(false);
        txtcodigoImpresora.setEnabled(false);
        txtnombreImpresora.setEnabled(true);
        txtdireccion.setEnabled(true);
        int fila =tbimpresora.rowAtPoint(evt.getPoint());

        txtcodigoImpresora.setText(tbimpresora.getValueAt(fila, 0).toString());
        txtnombreImpresora.setText(tbimpresora.getValueAt(fila, 1).toString());
        txtdireccion.setText(tbimpresora.getValueAt(fila, 2).toString());
    }//GEN-LAST:event_tbimpresoraMouseClicked

    private void txtcodigoImpresoraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoImpresoraKeyTyped
        Character c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }
    }//GEN-LAST:event_txtcodigoImpresoraKeyTyped

    private void txtnombreImpresoraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreImpresoraKeyTyped
        Character c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }
    }//GEN-LAST:event_txtnombreImpresoraKeyTyped

    private void txtdireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyTyped
         Character c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }
    }//GEN-LAST:event_txtdireccionKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmimpresora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmimpresora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmimpresora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmimpresora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmimpresora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmenu;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblnombre1;
    private java.awt.Panel panel2;
    private javax.swing.JTable tbimpresora;
    public static javax.swing.JTextField txtcodigoImpresora;
    public static javax.swing.JTextField txtdireccion;
    public static javax.swing.JTextField txtnombreImpresora;
    // End of variables declaration//GEN-END:variables
}
