/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTAS;

import DATOS.Vlogin;
import LOGICA.flogin;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class frmlogin extends javax.swing.JFrame {

    /**
     * Creates new form frmlogin
     */
    public frmlogin() {
        initComponents();
        this.setTitle("Control de Usuario");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        panel2 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtclave = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbusuario = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONTROL DE ACCESO");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(475, 150));
        setMinimumSize(new java.awt.Dimension(475, 150));
        setPreferredSize(new java.awt.Dimension(475, 150));
        getContentPane().setLayout(null);

        panel2.setBackground(new java.awt.Color(0, 102, 153));
        panel2.setForeground(new java.awt.Color(0, 255, 255));
        panel2.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(102, 153, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SISTEMA PUNTO DE VENTA MERASO ");
        jLabel1.setToolTipText("");
        panel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 460, 40);

        getContentPane().add(panel2);
        panel2.setBounds(0, 0, 590, 40);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("CONTRASENA");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 40, 82, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("USUARIO");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 56, 30);

        txtnombre.setText(" ");
        txtnombre.setToolTipText("NOMBRE DE USUARIO");
        txtnombre.setCaretPosition(0);
        txtnombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtnombre.setNextFocusableComponent(txtclave);
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });
        jPanel1.add(txtnombre);
        txtnombre.setBounds(100, 10, 200, 30);

        txtclave.setNextFocusableComponent(jButton1);
        jPanel1.add(txtclave);
        txtclave.setBounds(100, 40, 200, 30);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setText("SALIR");
        jButton2.setNextFocusableComponent(txtnombre);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(320, 40, 130, 30);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("ENTRAR");
        jButton1.setNextFocusableComponent(tbusuario);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(320, 10, 130, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 40, 460, 80);

        tbusuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbusuario);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(600, 260, 20, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        /*
            Verificaciond de acceso al menu principal
        */
        try {
                DefaultTableModel modelo;
                flogin funcion= new flogin();
                Vlogin dts = new Vlogin();
                
                dts.setNombre(txtnombre.getText());
                dts.setClave(txtclave.getText());
                //dts.setClave(txtclave1.getText());
                
                modelo=funcion.verificarUsurio(dts.getNombre(),dts.getClave());
                
                tbusuario.setModel(modelo);
               
                if (funcion.totalRegistros>0){
                    this.dispose();
                    frmmenu form= new frmmenu();
                    form.toFront();
                    form.setVisible(true);
                    frmmenu.lblcodigo.setText(tbusuario.getValueAt(0, 0).toString());
                    frmmenu.lblnombre.setText(tbusuario.getValueAt(0, 1).toString());
                    frmmenu.lblprivilegio.setText(tbusuario.getValueAt(0, 3).toString());
                    String privilegios= tbusuario.getValueAt(0, 3).toString();
                    if (frmmenu.lblprivilegio.getText().equals("ADMINISTRADOR")){
                        frmmenu.mnuConfiguracion.setEnabled(true);
                        frmmenu.mnuModulos.setEnabled(true);
                    }
                    else{
                        frmmenu.mnuConfiguracion.setEnabled(false);
                        frmmenu.mnuModulos.setEnabled(false);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "Combinacion Incorrecta", null, WIDTH, null);
                }   
                    
        } catch (Exception e) {
            
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        Character c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }
    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        
    }//GEN-LAST:event_txtnombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Panel panel2;
    private javax.swing.JTable tbusuario;
    private javax.swing.JPasswordField txtclave;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
