/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTAS;

import DATOS.vpaciente;
import LOGICA.fpaciente;
import static VISTAS.frmmenu.escritorio;
import java.sql.Date;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class frmpaciente extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmpaciente
     */
    public frmpaciente() {
        initComponents();
        inhabilitar();
    }
    
       private void inhabilitar (){
       //deshabilitar cajas de texto
        txtcodigoPaciente.setEnabled(false);
        txtcedulaPaciente.setEnabled(false);
        txtnombrePaciente.setEnabled(false);
        txtapellidoPaciente1.setEnabled(false);
        jdfechaNacimiento.setEnabled(false);
        txttelefono.setEnabled(false);
        txtdireccion.setEnabled(false);
        cbsexo.setEnabled(false);
      
        //deshabilitar botones
        btnguardar.setEnabled(false);
        btneliminar.setEnabled(false);
        btnmodificar.setEnabled(false);
        btncancelar.setEnabled(false);
        
    }
    private void nuevoCodigo(){
       int codigo=0;
       fpaciente funcion= new fpaciente();
       codigo=funcion.asignarCodigoPaciente();
       codigo=codigo+1; 
       txtcodigoPaciente.setText(String.valueOf(codigo));
       System.out.println(codigo);
   }
    void vaciarCajas(){
            //vaciar cajas de texto
        txtcodigoPaciente.setText("");
        txtcedulaPaciente.setText("");
        txtnombrePaciente.setText("");
        txtapellidoPaciente1.setText("");
        txttelefono.setText("");
        txtdireccion.setText("");
        cbsexo.setSelectedIndex(0);
    }
    public void habilitar (){
        //habilitar cajas de texto
        txtcodigoPaciente.setEnabled(true);
        txtcedulaPaciente.setEnabled(true);
        txtnombrePaciente.setEnabled(true);
        txtapellidoPaciente1.setEnabled(true);
        jdfechaNacimiento.setEnabled(true);
        txttelefono.setEnabled(true);
        txtdireccion.setEnabled(true);
        cbsexo.setEnabled(true);
        jdfechaNacimiento.setEnabled(true);
        //habilitar botones
        btnguardar.setEnabled(true);
        btnmenu.setEnabled(true);
        btneliminar.setEnabled(true);
        //vaciar cajas de texto
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new java.awt.Panel();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnmenu = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblcedula = new javax.swing.JLabel();
        txtcedulaPaciente = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        lblapellido = new javax.swing.JLabel();
        lblfechaNacimiento = new javax.swing.JLabel();
        txtcodigoPaciente = new javax.swing.JTextField();
        lblsexo = new javax.swing.JLabel();
        cbsexo = new javax.swing.JComboBox();
        lblnombres = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        lblnombres1 = new javax.swing.JLabel();
        txtnombrePaciente = new javax.swing.JTextField();
        txtapellidoPaciente1 = new javax.swing.JTextField();
        lblapellido1 = new javax.swing.JLabel();
        lblcodigo = new javax.swing.JLabel();
        jdfechaNacimiento = new com.toedter.calendar.JDateChooser();
        btnhabilitar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PACIENTE");
        setMaximumSize(new java.awt.Dimension(720, 270));
        setMinimumSize(new java.awt.Dimension(720, 270));
        setPreferredSize(new java.awt.Dimension(720, 270));
        getContentPane().setLayout(null);

        panel2.setBackground(new java.awt.Color(0, 102, 153));
        panel2.setLayout(null);

        btnnuevo.setBackground(new java.awt.Color(255, 255, 255));
        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/agregar-documento-simbolo-delineado.png"))); // NOI18N
        btnnuevo.setToolTipText("NUEVO REGISTRO");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        panel2.add(btnnuevo);
        btnnuevo.setBounds(0, 0, 50, 50);

        btnguardar.setBackground(new java.awt.Color(255, 255, 255));
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/guardar.png"))); // NOI18N
        btnguardar.setToolTipText("GUARDAR REGISTRO");
        btnguardar.setNextFocusableComponent(btnmodificar);
        btnguardar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/guardar.png"))); // NOI18N
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        panel2.add(btnguardar);
        btnguardar.setBounds(50, 0, 50, 50);

        btnmodificar.setBackground(new java.awt.Color(255, 255, 255));
        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/archivo-nuevo.png"))); // NOI18N
        btnmodificar.setToolTipText("MODIFICAR REGISTRO");
        btnmodificar.setNextFocusableComponent(btncancelar);
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        panel2.add(btnmodificar);
        btnmodificar.setBounds(100, 0, 50, 50);

        btncancelar.setBackground(new java.awt.Color(255, 255, 255));
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/expediente.png"))); // NOI18N
        btncancelar.setToolTipText("CANCELAR REGISTRO");
        btncancelar.setNextFocusableComponent(btneliminar);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        panel2.add(btncancelar);
        btncancelar.setBounds(150, 0, 50, 50);

        btneliminar.setBackground(new java.awt.Color(255, 255, 255));
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/cubo-de-basura.png"))); // NOI18N
        btneliminar.setToolTipText("ELIMINAR REGISTRO");
        btneliminar.setNextFocusableComponent(btnbuscar);
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        panel2.add(btneliminar);
        btneliminar.setBounds(200, 0, 50, 50);

        btnmenu.setBackground(new java.awt.Color(255, 255, 255));
        btnmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/salida.png"))); // NOI18N
        btnmenu.setText("MENU");
        btnmenu.setToolTipText("IR A MENU");
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });
        panel2.add(btnmenu);
        btnmenu.setBounds(600, 0, 100, 50);

        btnbuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/buscar.png"))); // NOI18N
        btnbuscar.setToolTipText("BUSCAR EN REGISTROS");
        btnbuscar.setNextFocusableComponent(btnmenu);
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        panel2.add(btnbuscar);
        btnbuscar.setBounds(250, 0, 50, 50);

        getContentPane().add(panel2);
        panel2.setBounds(0, 0, 710, 50);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DETALLE DE PACIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.setLayout(null);

        lblcedula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcedula.setText("CEDULA");
        jPanel1.add(lblcedula);
        lblcedula.setBounds(230, 20, 60, 30);

        txtcedulaPaciente.setNextFocusableComponent(cbsexo);
        txtcedulaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcedulaPacienteActionPerformed(evt);
            }
        });
        txtcedulaPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcedulaPacienteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcedulaPacienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcedulaPacienteKeyTyped(evt);
            }
        });
        jPanel1.add(txtcedulaPaciente);
        txtcedulaPaciente.setBounds(300, 20, 160, 30);

        txttelefono.setNextFocusableComponent(txtdireccion);
        txttelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttelefonoFocusLost(evt);
            }
        });
        txttelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefonoActionPerformed(evt);
            }
        });
        txttelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttelefonoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttelefonoKeyReleased(evt);
            }
        });
        jPanel1.add(txttelefono);
        txttelefono.setBounds(390, 100, 300, 30);

        lblapellido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblapellido.setText("DIRECCION");
        jPanel1.add(lblapellido);
        lblapellido.setBounds(10, 140, 90, 30);

        lblfechaNacimiento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblfechaNacimiento.setText("FEC. NAC:");
        jPanel1.add(lblfechaNacimiento);
        lblfechaNacimiento.setBounds(10, 100, 70, 30);

        txtcodigoPaciente.setNextFocusableComponent(txtcedulaPaciente);
        txtcodigoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoPacienteActionPerformed(evt);
            }
        });
        txtcodigoPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcodigoPacienteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcodigoPacienteKeyReleased(evt);
            }
        });
        jPanel1.add(txtcodigoPaciente);
        txtcodigoPaciente.setBounds(90, 20, 130, 30);

        lblsexo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblsexo.setText("SEXO");
        jPanel1.add(lblsexo);
        lblsexo.setBounds(470, 20, 50, 30);

        cbsexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MASCULINO", "FEMENINO" }));
        cbsexo.setNextFocusableComponent(jdfechaNacimiento);
        cbsexo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbsexoItemStateChanged(evt);
            }
        });
        cbsexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsexoActionPerformed(evt);
            }
        });
        jPanel1.add(cbsexo);
        cbsexo.setBounds(510, 20, 180, 30);

        lblnombres.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblnombres.setText("TELEFONO");
        jPanel1.add(lblnombres);
        lblnombres.setBounds(310, 100, 60, 30);

        txtdireccion.setNextFocusableComponent(btnguardar);
        txtdireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdireccionFocusLost(evt);
            }
        });
        txtdireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdireccionActionPerformed(evt);
            }
        });
        txtdireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdireccionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdireccionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdireccionKeyTyped(evt);
            }
        });
        jPanel1.add(txtdireccion);
        txtdireccion.setBounds(90, 140, 600, 30);

        lblnombres1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblnombres1.setText("NOMBRES");
        jPanel1.add(lblnombres1);
        lblnombres1.setBounds(10, 60, 60, 30);

        txtnombrePaciente.setNextFocusableComponent(txtapellidoPaciente1);
        txtnombrePaciente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnombrePacienteFocusLost(evt);
            }
        });
        txtnombrePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombrePacienteActionPerformed(evt);
            }
        });
        txtnombrePaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnombrePacienteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnombrePacienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombrePacienteKeyTyped(evt);
            }
        });
        jPanel1.add(txtnombrePaciente);
        txtnombrePaciente.setBounds(90, 60, 210, 30);

        txtapellidoPaciente1.setNextFocusableComponent(txttelefono);
        txtapellidoPaciente1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtapellidoPaciente1FocusLost(evt);
            }
        });
        txtapellidoPaciente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellidoPaciente1ActionPerformed(evt);
            }
        });
        txtapellidoPaciente1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtapellidoPaciente1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtapellidoPaciente1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidoPaciente1KeyTyped(evt);
            }
        });
        jPanel1.add(txtapellidoPaciente1);
        txtapellidoPaciente1.setBounds(390, 60, 300, 30);

        lblapellido1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblapellido1.setText("APELLIDOS");
        jPanel1.add(lblapellido1);
        lblapellido1.setBounds(310, 60, 90, 30);

        lblcodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcodigo.setText("CODIGO");
        jPanel1.add(lblcodigo);
        lblcodigo.setBounds(10, 20, 60, 30);

        jdfechaNacimiento.setNextFocusableComponent(txtnombrePaciente);
        jPanel1.add(jdfechaNacimiento);
        jdfechaNacimiento.setBounds(90, 100, 210, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 50, 700, 180);

        btnhabilitar.setText("habilitar");
        btnhabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhabilitarActionPerformed(evt);
            }
        });
        getContentPane().add(btnhabilitar);
        btnhabilitar.setBounds(720, 120, 71, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed

        habilitar();
        vaciarCajas();
        txtcodigoPaciente.requestFocus();
        btnmodificar.setEnabled(false);
        btnmenu.setEnabled(false);
        btnnuevo.setEnabled(false);
        btneliminar.setEnabled(false);
        btncancelar.setEnabled(true);
        btnguardar.setEnabled(true);
        nuevoCodigo();
        
        txtcedulaPaciente.requestFocus();
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        if (txtcodigoPaciente.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un nombre para el estudio");
            txtcodigoPaciente.requestFocus();
            return;
        }
        if (txtcedulaPaciente.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un Codigo para la estudio");
            txtcedulaPaciente.requestFocus();
            return;
        }
        if (txtnombrePaciente.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un nombre para el estudio");
            txtnombrePaciente.requestFocus();
            return;
        }
        if (txtapellidoPaciente1.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un nombre para el estudio");
            txtapellidoPaciente1.requestFocus();
            return;
        }
        if (txttelefono.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un nombre para el estudio");
            txttelefono.requestFocus();
            return;
        }
        
        if (txtdireccion.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un nombre para el estudio");
            txtdireccion.requestFocus();
            return;
        }
       
        try {
            vpaciente dts = new vpaciente();
            fpaciente func = new fpaciente();

            dts.setCodigoPaciente(Integer.parseInt(txtcodigoPaciente.getText()));
            dts.setCedula((txtcedulaPaciente.getText()));
            dts.setNombres((txtnombrePaciente.getText()));
            dts.setApellidos((txtapellidoPaciente1.getText()));

            /*
             CODIGO DEL CALENDARIO
             */
            Calendar calendario;
            int d, m, a;
            calendario = jdfechaNacimiento.getCalendar();
            d = calendario.get(Calendar.DAY_OF_MONTH);
            m = calendario.get(Calendar.MONTH);
            a = calendario.get(Calendar.YEAR) - 1900;

            dts.setFechaNacimiento(new Date(a, m, d));
            dts.setTelefono(txttelefono.getText());
            dts.setDireccion(txtdireccion.getText());
            dts.setSexo(cbsexo.getSelectedItem().toString());

            func.insertar(dts);
            JOptionPane.showMessageDialog(rootPane, "Se ha almacenado el registro exitosomente.");
            inhabilitar();
            //habilitar botones
            btnmenu.setEnabled(true);
            btnnuevo.setEnabled(true);
            //ihabilitar botones
            btnguardar.setEnabled(false);
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(rootPane, "Se ha producido un error al  almacenar el registro.");
        }
        
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        if (txtcodigoPaciente.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un nombre para el estudio");
            txtcodigoPaciente.requestFocus();
            return;
        }
        if (txtcedulaPaciente.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un Codigo para la estudio");
            txtcedulaPaciente.requestFocus();
            return;
        }
        if (txtnombrePaciente.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un nombre para el estudio");
            txtnombrePaciente.requestFocus();
            return;
        }
        if (txtapellidoPaciente1.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un nombre para el estudio");
            txtapellidoPaciente1.requestFocus();
            return;
        }
        if (txttelefono.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un nombre para el estudio");
            txttelefono.requestFocus();
            return;
        }
        
        if (txtdireccion.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un nombre para el estudio");
            txtdireccion.requestFocus();
            return;
        }
        try {
            vpaciente dts = new vpaciente();
            fpaciente func = new fpaciente();

            dts.setCodigoPaciente(Integer.parseInt(txtcodigoPaciente.getText()));
            dts.setCedula((txtcedulaPaciente.getText()));
            dts.setNombres((txtnombrePaciente.getText()));
            dts.setApellidos((txtapellidoPaciente1.getText()));
            /*
             CODIGO DEL CALENDARIO
             */
            Calendar calendario;
            int d, m, a;
            calendario = jdfechaNacimiento.getCalendar();
            d = calendario.get(Calendar.DAY_OF_MONTH);
            m = calendario.get(Calendar.MONTH);
            a = calendario.get(Calendar.YEAR) - 1900;

            dts.setFechaNacimiento(new Date(a, m, d));
            dts.setTelefono(txttelefono.getText());
            dts.setDireccion(txtdireccion.getText());
            dts.setSexo(cbsexo.getSelectedItem().toString());


            func.modificar(dts);
            JOptionPane.showMessageDialog(rootPane, "Registro modificado exitosamente.");
            inhabilitar();
            btnmenu.setEnabled(true);
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(rootPane, "El registro no se ha podido modificar.");
        }
        
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(rootPane, "Operacion cancelada."); 
        btnmenu.setEnabled(true);
        btnnuevo.setEnabled(true);
        vaciarCajas();
        inhabilitar ();

    }//GEN-LAST:event_btncancelarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        if (!txtcodigoPaciente.getText().equals("")) {

            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Seguro que quiere eliminar este registro?", "Confirmar", 2);

            if (confirmacion==0) {
                try {
                    fpaciente func = new fpaciente();
                    vpaciente dts = new vpaciente();

                    dts.setCodigoPaciente(Integer.parseInt(txtcodigoPaciente.getText()));
                    func.eliminar(dts);
                    //mostrar("");
                    inhabilitar();
                    btnmenu.setEnabled(true);
                    vaciarCajas();
                    
                    JOptionPane.showMessageDialog(rootPane, "Registro eliminado exitosamente.");
                } catch (Exception e) {

                    JOptionPane.showMessageDialog(rootPane, "No se ha podido eliminar el registro");
                }
                
            }
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
        // TODO add your handling code here:
        if(!(txtcedulaPaciente.getText().equals(""))){
        frmbuscarPaciente.txtbuscar.setText(txtcedulaPaciente.getText());
        frmbuscarPaciente.btnbuscar.doClick();
        this.dispose();
        }
        else{
        this.dispose();
        }
    }//GEN-LAST:event_btnmenuActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        frmconsultaPaciente form = new frmconsultaPaciente();
        escritorio.add(form);
        form.toFront();
        form.setSize(840, 540);
        form.setVisible(true); 
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void txtcedulaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcedulaPacienteActionPerformed
        // TODO add your handling code here:
        txttelefono.grabFocus();
    }//GEN-LAST:event_txtcedulaPacienteActionPerformed

    private void txtcedulaPacienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedulaPacienteKeyPressed

    }//GEN-LAST:event_txtcedulaPacienteKeyPressed

    private void txtcedulaPacienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedulaPacienteKeyReleased

    }//GEN-LAST:event_txtcedulaPacienteKeyReleased

    private void txttelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttelefonoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonoFocusLost

    private void txttelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonoActionPerformed

    private void txttelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonoKeyPressed

    private void txttelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonoKeyReleased

    private void txtcodigoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoPacienteActionPerformed

    private void txtcodigoPacienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoPacienteKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoPacienteKeyPressed

    private void txtcodigoPacienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoPacienteKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoPacienteKeyReleased

    private void cbsexoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbsexoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbsexoItemStateChanged

    private void cbsexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsexoActionPerformed
        
    }//GEN-LAST:event_cbsexoActionPerformed

    private void txtdireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdireccionFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionFocusLost

    private void txtdireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionActionPerformed

    private void txtdireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionKeyPressed

    private void txtdireccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionKeyReleased

    private void txtnombrePacienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnombrePacienteFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombrePacienteFocusLost

    private void txtnombrePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombrePacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombrePacienteActionPerformed

    private void txtnombrePacienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombrePacienteKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombrePacienteKeyPressed

    private void txtnombrePacienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombrePacienteKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombrePacienteKeyReleased

    private void txtapellidoPaciente1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtapellidoPaciente1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidoPaciente1FocusLost

    private void txtapellidoPaciente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellidoPaciente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidoPaciente1ActionPerformed

    private void txtapellidoPaciente1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidoPaciente1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidoPaciente1KeyPressed

    private void txtapellidoPaciente1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidoPaciente1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidoPaciente1KeyReleased

    private void btnhabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhabilitarActionPerformed
        // TODO add your handling code here:
        habilitar();
        btnguardar.setEnabled(false);
        btnmenu.setEnabled(false);
    }//GEN-LAST:event_btnhabilitarActionPerformed

    private void txtapellidoPaciente1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidoPaciente1KeyTyped
        Character c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }
    }//GEN-LAST:event_txtapellidoPaciente1KeyTyped

    private void txtnombrePacienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombrePacienteKeyTyped
        Character c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }
    }//GEN-LAST:event_txtnombrePacienteKeyTyped

    private void txtcedulaPacienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedulaPacienteKeyTyped
        Character c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }
    }//GEN-LAST:event_txtcedulaPacienteKeyTyped

    private void txtdireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyTyped
        Character c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }
    }//GEN-LAST:event_txtdireccionKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmpaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmpaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmpaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmpaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmpaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnbuscar;
    public static javax.swing.JButton btncancelar;
    public static javax.swing.JButton btneliminar;
    public static javax.swing.JButton btnguardar;
    public static javax.swing.JButton btnhabilitar;
    public static javax.swing.JButton btnmenu;
    public static javax.swing.JButton btnmodificar;
    public static javax.swing.JButton btnnuevo;
    public static javax.swing.JComboBox cbsexo;
    private javax.swing.JPanel jPanel1;
    public static com.toedter.calendar.JDateChooser jdfechaNacimiento;
    private javax.swing.JLabel lblapellido;
    private javax.swing.JLabel lblapellido1;
    private javax.swing.JLabel lblcedula;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JLabel lblfechaNacimiento;
    private javax.swing.JLabel lblnombres;
    private javax.swing.JLabel lblnombres1;
    private javax.swing.JLabel lblsexo;
    private java.awt.Panel panel2;
    public static javax.swing.JTextField txtapellidoPaciente1;
    public static javax.swing.JTextField txtcedulaPaciente;
    public static javax.swing.JTextField txtcodigoPaciente;
    public static javax.swing.JTextField txtdireccion;
    public static javax.swing.JTextField txtnombrePaciente;
    public static javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
