
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTAS;

import DATOS.vusuario;
import LOGICA.fusuario;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author user
 */
public class frmusuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmusuario
     */
    public frmusuario() {
        initComponents();
        inhabilitar();
        mostrar("");
    }
    
    private void sizetable(){
    TableColumnModel columnModel = tablaUsuarios.getColumnModel();
    columnModel.getColumn(0).setPreferredWidth(60);
    columnModel.getColumn(1).setPreferredWidth(100);
    columnModel.getColumn(2).setPreferredWidth(100);
    columnModel.getColumn(3).setPreferredWidth(100);
    }

    
   private void inhabilitar (){
       //deshabilitar cajas de texto
        txtcodigoUsuario.setEnabled(false);
        txtnombre.setEnabled(false);
        txtclave.setEnabled(false);
        txtprivilegios.setEnabled(false);
        

        //deshabilitar botones
        btnguardar.setEnabled(false);
        btneliminar.setEnabled(false);
        btnmodificar.setEnabled(false);
        btncancelar.setEnabled(false);
        
        //vaciar cajas de texto
        txtcodigoUsuario.setText("");
        txtnombre.setText("");
        txtclave.setText("");
        txtprivilegios.setText("");
        txtprivilegios.setText("");
        
    }
   
    void habilitar (){
        //habilitar cajas de texto
        txtcodigoUsuario.setEnabled(true);
        txtnombre.setEnabled(true);
        txtclave.setEnabled(true);
        txtprivilegios.setEnabled(true);
        //habilitar botones
        btnguardar.setEnabled(true);
        btnmenu.setEnabled(true);
        btneliminar.setEnabled(true);
        //vaciar cajas de texto
        txtcodigoUsuario.setText("");
        txtnombre.setText("");
        txtclave.setText("");
        txtprivilegios.setText("");
        
    }
    
    private void mostrar (String buscar){
        try {
            DefaultTableModel modelo;
            fusuario func= new fusuario();
            modelo=func.mostrar(buscar);
            tablaUsuarios.setModel(modelo);
            lblTotal.setText(""+ Integer.toString(func.totalRegistros));   
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
            
        }
    
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new java.awt.Panel();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnmenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnbuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblcodigo = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        lblclave = new javax.swing.JLabel();
        lblprivilegios = new javax.swing.JLabel();
        txtcodigoUsuario = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtclave = new javax.swing.JTextField();
        txtprivilegios = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setTitle("Mantenimiento Usuario");
        setMaximumSize(new java.awt.Dimension(530, 510));
        setMinimumSize(new java.awt.Dimension(530, 510));
        setPreferredSize(new java.awt.Dimension(530, 510));
        getContentPane().setLayout(null);

        panel2.setBackground(new java.awt.Color(0, 102, 153));
        panel2.setLayout(null);

        btnnuevo.setBackground(new java.awt.Color(255, 255, 255));
        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/agregar-documento-simbolo-delineado.png"))); // NOI18N
        btnnuevo.setToolTipText("NUEVO REGISTRO");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        panel2.add(btnnuevo);
        btnnuevo.setBounds(0, 0, 50, 50);

        btnguardar.setBackground(new java.awt.Color(255, 255, 255));
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/guardar.png"))); // NOI18N
        btnguardar.setToolTipText("GUARDAR REGISTRO");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        panel2.add(btnguardar);
        btnguardar.setBounds(50, 0, 50, 50);

        btnmodificar.setBackground(new java.awt.Color(255, 255, 255));
        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/archivo-nuevo.png"))); // NOI18N
        btnmodificar.setToolTipText("MODIFICAR REGISTRO");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        panel2.add(btnmodificar);
        btnmodificar.setBounds(100, 0, 50, 50);

        btncancelar.setBackground(new java.awt.Color(255, 255, 255));
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/expediente.png"))); // NOI18N
        btncancelar.setToolTipText("CANCELAR REGISTRO");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        panel2.add(btncancelar);
        btncancelar.setBounds(150, 0, 50, 50);

        btneliminar.setBackground(new java.awt.Color(255, 255, 255));
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/cubo-de-basura.png"))); // NOI18N
        btneliminar.setToolTipText("ELIMINAR REGISTRO");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        panel2.add(btneliminar);
        btneliminar.setBounds(200, 0, 50, 50);

        btnmenu.setBackground(new java.awt.Color(255, 255, 255));
        btnmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/salida.png"))); // NOI18N
        btnmenu.setText("MENU");
        btnmenu.setToolTipText("IR A MENU");
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });
        panel2.add(btnmenu);
        btnmenu.setBounds(400, 0, 110, 50);

        getContentPane().add(panel2);
        panel2.setBounds(0, 0, 600, 50);

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "USUARIO", "CLAVE", "PRIVILEGIOS"
            }
        ));
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 220, 500, 230);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("USUARIOS REGISTRADOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 180, 160, 30);

        txtbuscar.setText(" ");
        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });
        txtbuscar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtbuscarPropertyChange(evt);
            }
        });
        getContentPane().add(txtbuscar);
        txtbuscar.setBounds(330, 180, 120, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("TOTAL DE REGISTROS:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(260, 450, 140, 20);

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 0, 0));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal.setText("0");
        getContentPane().add(lblTotal);
        lblTotal.setBounds(400, 450, 110, 20);

        btnbuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARCHIVOS/buscar.png"))); // NOI18N
        btnbuscar.setToolTipText("BUSCAR USUARIO");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnbuscar);
        btnbuscar.setBounds(450, 170, 60, 50);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DETALLE DE USUARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.setLayout(null);

        lblcodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcodigo.setText("CODIGO ");
        jPanel1.add(lblcodigo);
        lblcodigo.setBounds(10, 20, 60, 30);

        lblusuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblusuario.setText("USUARIO");
        jPanel1.add(lblusuario);
        lblusuario.setBounds(10, 60, 60, 30);

        lblclave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblclave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblclave.setText("CLAVE");
        jPanel1.add(lblclave);
        lblclave.setBounds(220, 60, 90, 30);

        lblprivilegios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblprivilegios.setText("PRIVILEGIOS");
        jPanel1.add(lblprivilegios);
        lblprivilegios.setBounds(220, 20, 80, 30);

        txtcodigoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoUsuarioActionPerformed(evt);
            }
        });
        txtcodigoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcodigoUsuarioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcodigoUsuarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodigoUsuarioKeyTyped(evt);
            }
        });
        jPanel1.add(txtcodigoUsuario);
        txtcodigoUsuario.setBounds(70, 20, 130, 30);

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });
        jPanel1.add(txtnombre);
        txtnombre.setBounds(70, 60, 130, 30);

        txtclave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclaveActionPerformed(evt);
            }
        });
        txtclave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtclaveKeyTyped(evt);
            }
        });
        jPanel1.add(txtclave);
        txtclave.setBounds(310, 60, 170, 30);

        txtprivilegios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprivilegiosActionPerformed(evt);
            }
        });
        txtprivilegios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtprivilegiosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprivilegiosKeyTyped(evt);
            }
        });
        jPanel1.add(txtprivilegios);
        txtprivilegios.setBounds(310, 20, 170, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 60, 500, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed

        habilitar();
        txtcodigoUsuario.requestFocus();
        btnmodificar.setEnabled(false);
        btnmenu.setEnabled(false);
        btnnuevo.setEnabled(false);
        btneliminar.setEnabled(false);
        btncancelar.setEnabled(true);
        btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        if (txtcodigoUsuario.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un Codigo para el usuario");
            txtcodigoUsuario.requestFocus();
            return;
        }

        if (txtnombre.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un nombre de usuario");
            txtnombre.requestFocus();
            return;
        }
        if (txtclave.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar una clave");
            txtclave.requestFocus();
            return;
        }
        if (txtprivilegios.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes determinar los privilegios de este Usuario");
            txtprivilegios.requestFocus();
            return;
        }
        try {
            vusuario dts = new vusuario();
            fusuario func = new fusuario();

            dts.setCodigoUsuario(Integer.parseInt(txtcodigoUsuario.getText()));
            dts.setNombre(txtnombre.getText());
            dts.setClave(txtclave.getText());
            dts.setPrivilegio(txtprivilegios.getText());

            func.insertar(dts);
            mostrar("");
            inhabilitar();
            //habilitar botones
            btnmenu.setEnabled(true);
            btnnuevo.setEnabled(true);
            //ihabilitar botones
            btnguardar.setEnabled(false);

            sizetable();
            JOptionPane.showMessageDialog(rootPane, "Se ha almacenado el registro exitosamente.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Ha ocurrido un error al intentar guardar el registro.");
        }
        
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        if (txtcodigoUsuario.getText().length()==0){
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar un codigo para el usuario");
            txtcodigoUsuario.requestFocus();
            return;
        }

        if (txtnombre.getText().length()==0){
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar un nombre de usuario");
            txtnombre.requestFocus();
            return;
        }
        if (txtclave.getText().length()==0){
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar una clave");
            txtclave.requestFocus();
            return;
        }
        if (txtprivilegios.getText().length()==0){
            JOptionPane.showConfirmDialog(rootPane, "Debes determinar los privilegios de este Usuario");
            txtprivilegios.requestFocus();
            return;
        }
        try {
            vusuario dts = new vusuario();
            fusuario func = new fusuario();

            dts.setCodigoUsuario(Integer.parseInt(txtcodigoUsuario.getText()));
            dts.setNombre(txtnombre.getText());
            dts.setClave(txtclave.getText());
            dts.setPrivilegio(txtprivilegios.getText());

            func.modificar(dts);
            mostrar("");
            inhabilitar();
            btnmenu.setEnabled(true);
            sizetable();
            JOptionPane.showMessageDialog(rootPane, "Se ha modificado el registro exitosamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Ha ocurrido un error al intentar modificar el registro.");
        }

        
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        inhabilitar ();
        btnmenu.setEnabled(true);
        btnnuevo.setEnabled(true);
        mostrar("");
        sizetable();
        JOptionPane.showMessageDialog(rootPane, "Se ha cancelado la operacion.");

    }//GEN-LAST:event_btncancelarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        if (!txtcodigoUsuario.getText().equals("")) {

            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Seguro que quiere eliminar este registro?", "Confirmar", 2);

            if (confirmacion==0) {
                try {
                    fusuario func = new fusuario();
                    vusuario dts = new vusuario();

                    dts.setCodigoUsuario(Integer.parseInt(txtcodigoUsuario.getText()));
                    func.eliminar(dts);
                    mostrar("");
                    inhabilitar();
                    btnmenu.setEnabled(true);
                    sizetable();
                    JOptionPane.showMessageDialog(rootPane, "Se ha eliminado el registro.");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Ha ocurrido un error al intentar eliminar el usuario");
                }
                
            }
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnmenuActionPerformed

    private void tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMouseClicked
        // TODO add your handling code here:
        //habilar los elementos para su modificacion
        btnmodificar.setEnabled(true);
        btneliminar.setEnabled(true);
        btncancelar.setEnabled(true);
        btnmenu.setEnabled(false);
        txtcodigoUsuario.setEnabled(true);
        txtnombre.setEnabled(true);
        txtclave.setEnabled(true);
        txtprivilegios.setEnabled(true);

        int fila =tablaUsuarios.rowAtPoint(evt.getPoint());

        txtcodigoUsuario.setText(tablaUsuarios.getValueAt(fila, 0).toString());
        txtnombre.setText(tablaUsuarios.getValueAt(fila, 1).toString());
        txtclave.setText(tablaUsuarios.getValueAt(fila, 2).toString());
        txtprivilegios.setText(tablaUsuarios.getValueAt(fila, 3).toString());

    }//GEN-LAST:event_tablaUsuariosMouseClicked

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void txtbuscarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtbuscarPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarPropertyChange

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        try {
            mostrar(txtbuscar.getText());
        } catch (Exception e) {
        }
        

    }//GEN-LAST:event_btnbuscarActionPerformed

    private void txtcodigoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoUsuarioActionPerformed
        // TODO add your handling code here:
        txtnombre.grabFocus();
    }//GEN-LAST:event_txtcodigoUsuarioActionPerformed

    private void txtcodigoUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoUsuarioKeyPressed

    }//GEN-LAST:event_txtcodigoUsuarioKeyPressed

    private void txtcodigoUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoUsuarioKeyReleased

    }//GEN-LAST:event_txtcodigoUsuarioKeyReleased

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
        txtprivilegios.grabFocus();
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtclaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclaveActionPerformed
        // TODO add your handling code here:
        txtclave.transferFocus();
    }//GEN-LAST:event_txtclaveActionPerformed

    private void txtprivilegiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprivilegiosActionPerformed
        txtclave.grabFocus();
    }//GEN-LAST:event_txtprivilegiosActionPerformed

    private void txtprivilegiosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprivilegiosKeyPressed

    }//GEN-LAST:event_txtprivilegiosKeyPressed

    private void txtcodigoUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoUsuarioKeyTyped
        Character c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }
    }//GEN-LAST:event_txtcodigoUsuarioKeyTyped

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        Character c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }
    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtprivilegiosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprivilegiosKeyTyped
        Character c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }
    }//GEN-LAST:event_txtprivilegiosKeyTyped

    private void txtclaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtclaveKeyTyped
        Character c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }
    }//GEN-LAST:event_txtclaveKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmusuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmusuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmusuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmusuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmusuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmenu;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblclave;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JLabel lblprivilegios;
    private javax.swing.JLabel lblusuario;
    private java.awt.Panel panel2;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtclave;
    private javax.swing.JTextField txtcodigoUsuario;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtprivilegios;
    // End of variables declaration//GEN-END:variables
}
